# Draft Queries
Requires `draft_analysis.py` in the same folder.

In [1]:
from draft_analysis import *

site = connect_to_leaguepedia()

✅ Connexion établie avec Leaguepedia

## ⚙️ Config

In [3]:
#TOURNAMENTS = ["LEC 2026 Versus", "LEC 2026 Versus Playoffs", "LEC 2026 Spring"]
#TOURNAMENTS = ["LEC 2026 Spring"]
TOURNAMENTS = ["LFL 2026 Invitational", "LFL 2026 Spring", "EM 2026 Winter", "Esports World Cup 2026 Online Qualifier: EMEA"]

PATCHES     = None          # ex: ["25.4", "25.5"] or None for all
TEAM        = "Galions"          # ex: "SK Gaming" or None for all
#TEAM = None
LIMIT       = 500          # ex: 100 or None for all

# ── Auto filename builder ────────────────────────────────────────────────────
# Produces a suffix like: LEC2026Versus-LCKCup2026_SKGaming_p25.4-25.5
# Every section below uses it automatically.

def _build_suffix(tournaments=None, team=None, patches=None):
    parts = []
    if tournaments:
        parts.append("-".join(t.replace(" ", "").replace(":", "_") for t in tournaments))
    if team:
        parts.append(team.replace(" ", ""))
    if patches:
        parts.append("p" + "-".join(patches))
    return "_".join(parts)

SUFFIX = _build_suffix(TOURNAMENTS, TEAM, PATCHES)
print(f"📁 File suffix: {SUFFIX}")

📁 File suffix: LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier_EMEA_Galions

In [4]:
df = scrape_draft_data(site, TOURNAMENTS, limit=500)
df_filtered = filter_dataframe(df, team_filter=TEAM)
df_filtered

============================================================
🔍 Traitement du tournoi: LFL 2026 Invitational
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 97 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (97 matchs)
✅ LFL 2026 Invitational: 97 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LFL 2026 Spring
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 40 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (40 matchs)
✅ LFL 2026 Spring: 40 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: EM 2026 Winter
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 174 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (174 matchs)
✅ EM 2026 Winter: 174 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: Esports World Cup 2026 Online Qualifier: EMEA
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 19 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (19 matchs)
✅ Esports World Cup 2026 Online Qualifier: EMEA: 19 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 330 matchs
📊 Filtré par équipe: Galions (55 games)

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
4,LFL/2026 Season/Invitational_Day 1_5_1,26.1,Galions,Caldya Esport,1,,Poppy,Malphite,Orianna,Alistar,...,Ryze,Mid,Vi,Jungle,K'Sante,Top,Miss Fortune,Bot,Nautilus,Support
10,LFL/2026 Season/Invitational_Day 3_1_1,26.2,Esprit Shōnen,Galions,2,,Ambessa,Orianna,Nocturne,Alistar,...,Yunara,Bot,Vi,Jungle,Taliyah,Mid,Renekton,Top,Braum,Support
25,LFL/2026 Season/Invitational_Week 1_1_1,26.2,TLN Pirates,Galions,2,,Malphite,Jarvan IV,Varus,Corki,...,Ambessa,Top,Azir,Mid,Pantheon,Jungle,Lucian,Bot,Milio,Support
33,LFL/2026 Season/Invitational_Week 1_9_1,26.2,ZYB Esport,Galions,2,,Ambessa,Orianna,Yone,K'Sante,...,Yunara,Bot,Jarvan IV,Jungle,Taliyah,Mid,Neeko,Support,Gnar,Top
37,LFL/2026 Season/Invitational_Week 1_13_1,26.2,Joblife,Galions,2,,Akali,Varus,Pantheon,Gnar,...,Ambessa,Jungle,Yunara,Bot,Nautilus,Support,Aurora,Top,Ahri,Mid
42,LFL/2026 Season/Invitational_Week 2_3_1,26.3,Solary,Galions,1,,Ambessa,Yunara,Orianna,Corki,...,Sejuani,Jungle,Yone,Mid,Aurora,Top,Lucian,Bot,Nautilus,Support
47,LFL/2026 Season/Invitational_Week 2_8_1,26.3,Galions,Lille Esport,1,,Ahri,Zoe,Rumble,Nautilus,...,Jarvan IV,Jungle,Sion,Top,Syndra,Mid,Rell,Support,Xayah,Bot
53,LFL/2026 Season/Invitational_Week 2_14_1,26.3,Galions,Skillcamp,1,,Rumble,Ambessa,Ryze,Nautilus,...,Taliyah,Mid,Jarvan IV,Jungle,Corki,Bot,Jax,Top,Nami,Support
57,LFL/2026 Season/Invitational_Week 2_18_1,26.3,Galions,Vitality.Bee,2,,Fiora,Rumble,Ambessa,Alistar,...,Varus,Bot,Orianna,Mid,Naafiri,Jungle,Renekton,Top,Rell,Support
60,LFL/2026 Season/Invitational_Week 3_1_1,26.3,Galions,BK ROG Esports,1,,Syndra,Ambessa,Varus,Nautilus,...,Azir,Mid,Yunara,Bot,Dr. Mundo,Jungle,Rakan,Support,Aatrox,Top
68,LFL/2026 Season/Invitational_Week 3_9_1,26.3,French Flair,Galions,1,,Jarvan IV,Ambessa,Yunara,Ezreal,...,Sion,Top,Ahri,Mid,Pantheon,Jungle,Corki,Bot,Renata Glasc,Support
71,LFL/2026 Season/Invitational_Tiebreakers_2_1,26.3,French Flair,Galions,2,,Jarvan IV,Yunara,Ambessa,Nami,...,Orianna,Mid,Corki,Bot,Gwen,Top,Nocturne,Jungle,Neeko,Support
72,LFL/2026 Season/Invitational_Tiebreakers_3_1,26.3,Joblife,Galions,2,,Varus,Ambessa,Sion,Neeko,...,Ornn,Top,Corki,Bot,Taliyah,Mid,Aatrox,Jungle,Nami,Support
81,LFL/2026 Season/Invitational_Round 2_1_1,26.4,Galions,Solary,2,,Varus,Ambessa,Xin Zhao,Rumble,...,Taliyah,Mid,Corki,Bot,Vi,Jungle,Nami,Support,Gwen,Top
82,LFL/2026 Season/Invitational_Round 2_1_2,26.4,Solary,Galions,2,,Ambessa,Nautilus,Sion,Neeko,...,Varus,Bot,Jarvan IV,Jungle,Ornn,Top,Alistar,Support,Aurora,Mid
83,LFL/2026 Season/Invitational_Round 2_1_3,26.4,Galions,Solary,2,,Ambessa,Nautilus,Xin Zhao,Braum,...,Anivia,Mid,Pantheon,Jungle,Sion,Top,Aphelios,Bot,Leona,Support
84,LFL/2026 Season/Invitational_Round 2_1_4,26.4,Solary,Galions,1,,Neeko,Braum,Ambessa,Lucian,...,Mel,Mid,Aatrox,Jungle,Jayce,Top,Rakan,Support,Xayah,Bot
89,LFL/2026 Season/Invitational_Round 3_1_1,26.4,Galions,French Flair,2,,Dr. Mundo,Azir,Jarvan IV,Bard,...,Xin Zhao,Jungle,Aurora,Mid,Sion,Top,Nautilus,Support,Ezreal,Bot
90,LFL/2026 Season/Invitational_Round 3_1_2,26.4,Galions,French Flair,1,,Dr. Mundo,Azir,Corki,Bard,...,Aatrox,Jungle,LeBlanc,Mid,Ambessa,Top,Zeri,Bot,Lulu,Support
91,LFL/2026 Season/Invitational_Round 3_1_3,26.4,French Flair,Galions,2,,Neeko,Nami,Orianna,Gnar,...,Jhin,Bot,Pantheon,Jungle,Bard,Support,Yorick,Top,Syndra,Mid
92,LFL/2026 Season/Invitational_Round 3_1_4,26.4,French Flair,Galions,1,,Caitlyn,Nami,Rumble,Ornn,...,Lucian,Bot,Milio,Support,Akali,Mid,Skarner,Jungle,Malphite,Top
93,LFL/2026 Season/Invitational_Round 3_1_5,26.4,Galions,French Flair,1,,Sylas,Azir,Dr. Mundo,Alistar,...,Kalista,Bot,Nocturne,Jungle,Mel,Mid,Karma,Support,Olaf,Top
94,LFL/2026 Season/Invitational_Finals_1_1,26.4,Galions,Solary,2,,Azir,Nautilus,Renekton,Ryze,...,Corki,Bot,Vi,Jungle,Pyke,Support,Ahri,Mid,Gnar,Top
95,LFL/2026 Season/Invitational_Finals_1_2,26.4,Solary,Galions,1,,Ambessa,Neeko,Varus,Nautilus,...,Ornn,Top,Pantheon,Jungle,Taliyah,Mid,Ezreal,Bot,Nami,Support
96,LFL/2026 Season/Invitational_Finals_1_3,26.4,Galions,Solary,2,,Azir,Jhin,Sion,Xayah,...,Syndra,Mid,Dr. Mundo,Jungle,Vayne,Top,Jinx,Bot,Rell,Support
100,LFL/2026 Season/Spring Split_Week 1_4_1,26.7,Solary,Galions,2,,Ambessa,Nautilus,Karma,Gnar,...,Ezreal,Bot,Xin Zhao,Jungle,Leona,Support,LeBlanc,Mid,Jayce,Top
106,LFL/2026 Season/Spring Split_Week 1_10_1,26.7,Ici Japon Corp. Esport,Galions,1,,Nautilus,Ezreal,Seraphine,Ambessa,...,Corki,Bot,Xin Zhao,Jungle,Nami,Support,LeBlanc,Mid,Gnar,Top
111,LFL/2026 Season/Spring Split_Week 1_15_1,26.7,Galions,Vitality.Bee,2,,Rumble,Nautilus,Ashe,Lulu,...,Yunara,Bot,Pantheon,Jungle,Fiora,Top,Zoe,Mid,Rell,Support
114,LFL/2026 Season/Spring Split_Week 2_3_1,26.7,Galions,ZYB Esport,1,,Nautilus,Kalista,Anivia,Bard,...,Rumble,Top,Galio,Mid,Caitlyn,Bot,Neeko,Support,Xin Zhao,Jungle
118,LFL/2026 Season/Spring Split_Week 2_7_1,26.7,Galions,Skillcamp,1,,Nautilus,Jarvan IV,Anivia,Rumble,...,Bard,Support,Ezreal,Bot,Nocturne,Jungle,Mel,Mid,Gnar,Top
123,LFL/2026 Season/Spring Split_Week 2_12_1,26.7,Galions,TLN Pirates,2,,Caitlyn,Nautilus,Pantheon,Sion,...,Karma,Support,Xin Zhao,Jungle,Yunara,Bot,Ahri,Mid,Rumble,Top
130,LFL/2026 Season/Spring Split_Week 3_4_1,26.8,Galions,Joblife,1,,Karma,Nautilus,Ahri,Aurora,...,Ashe,Bot,Xin Zhao,Jungle,Lulu,Support,Azir,Mid,Ambessa,Top
133,LFL/2026 Season/Spring Split_Week 3_7_1,26.8,Galions,Esprit Shōnen,1,,Varus,Nautilus,Anivia,Ahri,...,Ezreal,Bot,Pantheon,Jungle,Bard,Support,Azir,Mid,K'Sante,Top
155,EMEA Masters/2026 Season/Winter_Groups Day 1_5_1,26.5,Vantex Esports,Galions,2,,Varus,Yunara,Ambessa,Corki,...,Ornn,Top,Vi,Jungle,Ahri,Mid,Kai'Sa,Bot,Rell,Support
158,EMEA Masters/2026 Season/Winter_Groups Day 1_5_2,26.5,Galions,Vantex Esports,1,,Caitlyn,Ambessa,Azir,Naafiri,...,Viktor,Mid,Varus,Bot,Leona,Support,Aatrox,Jungle,Garen,Top
191,EMEA Masters/2026 Season/Winter_Groups Day 3_5_1,26.5,UCAM Esports,Galions,2,,Yunara,Corki,Renekton,Bard,...,Ryze,Mid,Zaahen,Top,Aatrox,Jungle,Neeko,Support,Xayah,Bot
194,EMEA Masters/2026 Season/Winter_Groups Day 3_5_2,26.5,Galions,UCAM Esports,1,,Rumble,Nocturne,Wukong,Gnar,...,Galio,Mid,Yunara,Bot,Trundle,Jungle,Jax,Top,Pyke,Support
228,EMEA Masters/2026 Season/Winter_Groups Day 5_4_1,26.5,UCAM Esports,Galions,2,,Neeko,Ryze,Renekton,Braum,...,Zaahen,Top,Yunara,Bot,Ahri,Mid,Pantheon,Jungle,Renata Glasc,Support
230,EMEA Masters/2026 Season/Winter_Groups Day 5_4_2,26.5,Galions,UCAM Esports,2,,Nocturne,Rumble,Jarvan IV,Lulu,...,Xin Zhao,Jungle,Viktor,Mid,Dr. Mundo,Top,Kalista,Bot,Rakan,Support
234,EMEA Masters/2026 Season/Winter_Groups Day 5_4_3,26.5,UCAM Esports,Galions,2,,Neeko,Akali,Gwen,Karma,...,Ryze,Mid,Aatrox,Jungle,Gnar,Top,Varus,Bot,Bard,Support
261,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Eintracht Spandau,1,,Rumble,Nautilus,Ezreal,Sion,...,Azir,Mid,Nami,Support,Corki,Bot,Xin Zhao,Jungle,Gnar,Top
262,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Eintracht Spandau,Galions,2,,Ashe,Karma,Vi,Aurora,...,Ambessa,Top,Kai'Sa,Bot,Leona,Support,Ahri,Mid,Qiyana,Jungle
267,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Ashe,Vi,LeBlanc,...,Ezreal,Bot,Pantheon,Jungle,Braum,Support,Mel,Mid,K'Sante,Top
270,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Vi,LeBlanc,Ornn,...,Wukong,Jungle,Corki,Bot,Aurora,Mid,Neeko,Support,Gnar,Top
272,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,French Flair,1,,Dr. Mundo,Azir,Karma,Anivia,...,Varus,Bot,Jarvan IV,Jungle,Nautilus,Support,Aurora,Mid,Volibear,Top
275,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,French Flair,Galions,2,,Gwen,Wukong,Yunara,Vi,...,Ashe,Bot,Seraphine,Support,Ahri,Mid,Aatrox,Jungle,Renekton,Top
288,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Solary,Galions,2,,Ambessa,Karma,Vi,Ahri,...,Ezreal,Bot,Xin Zhao,Jungle,Nautilus,Support,Taliyah,Mid,Ornn,Top
289,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,2,,Azir,Ahri,Jarvan IV,Aurora,...,Ashe,Bot,Seraphine,Support,Pantheon,Jungle,Viktor,Mid,K'Sante,Top
291,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Karma,Corki,Dr. Mundo,...,Lucian,Bot,Nami,Support,Cassiopeia,Mid,Skarner,Jungle,Yorick,Top
293,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Ahri,Karma,Alistar,...,Kai'Sa,Bot,Aurora,Mid,Sion,Top,Rell,Support,Viego,Jungle
308,EMEA Masters/2026 Season/Winter_Finals_1_1,26.8,Galions,Solary,2,,Rumble,Xin Zhao,Ryze,Vayne,...,Pantheon,Jungle,Caitlyn,Bot,Rell,Support,Ahri,Mid,K'Sante,Top
309,EMEA Masters/2026 Season/Winter_Finals_1_2,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Xin Zhao,Ornn,...,Nocturne,Jungle,Nami,Support,Lucian,Bot,LeBlanc,Mid,Ambessa,Top
310,EMEA Masters/2026 Season/Winter_Finals_1_3,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Neeko,Rakan,...,Varus,Bot,Vi,Jungle,Taliyah,Mid,Leona,Support,Gwen,Top
311,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Natus Vincere,Galions,1,,Nautilus,Jarvan IV,Ryze,Nocturne,...,Ashe,Bot,Seraphine,Support,Aurora,Mid,Aatrox,Jungle,Gnar,Top
313,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Galions,Natus Vincere,2,,Nautilus,Karma,Varus,K'Sante,...,Yunara,Bot,Lulu,Support,Anivia,Mid,Ornn,Top,Graves,Jungle

In [5]:
FirstPick_List = df_filtered[
    (df_filtered['Team1'] == TEAM) & 
    (df_filtered['Team1Pick1'] != '')
]['Team1Pick1']

counts = FirstPick_List.value_counts()
counts

Team1Pick1
Ryze         6
Yunara       4
Orianna      3
Jarvan IV    3
Aurora       3
Ezreal       2
Varus        1
Azir         1
Maokai       1
Pantheon     1
Vi           1
Corki        1
Rumble       1
Name: count, dtype: int64

In [6]:
FirstPick_List_G1 = df_filtered[
    (df_filtered['Team1'] == TEAM) & 
    (df_filtered['Team1Pick1'] != '') &
    (df_filtered['GameId'].str.endswith('_1'))
]['Team1Pick1']

counts = FirstPick_List_G1.value_counts()
counts

Team1Pick1
Yunara       4
Ryze         3
Orianna      2
Jarvan IV    2
Ezreal       2
Varus        1
Azir         1
Pantheon     1
Aurora       1
Name: count, dtype: int64

---
## 1 · Draft cards
Visualise every draft as a card. Set `FILTER_CHAMPION` / `HIGHLIGHT_CHAMPION` as needed.

In [7]:
FILTER_CHAMPION    = None   # ex: "Azir"  → only games where Azir appears
HIGHLIGHT_CHAMPION = None   # ex: "Azir"  → highlight Azir in yellow

_suffix = _build_suffix(TOURNAMENTS, TEAM, PATCHES)
if FILTER_CHAMPION:
    _suffix += f"_{FILTER_CHAMPION}"

analyze_drafts(
    site,
    tournaments        = TOURNAMENTS,
    output_filename    = f"drafts_{_suffix}.html",
    team_filter        = TEAM,
    patches            = PATCHES,
    filter_champion    = FILTER_CHAMPION,
    highlight_champion = HIGHLIGHT_CHAMPION,
    limit              = 500,
)

============================================================
🔍 Traitement du tournoi: LFL 2026 Invitational
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 97 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (97 matchs)
✅ LFL 2026 Invitational: 97 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LFL 2026 Spring
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 40 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (40 matchs)
✅ LFL 2026 Spring: 40 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: EM 2026 Winter
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 174 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (174 matchs)
✅ EM 2026 Winter: 174 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: Esports World Cup 2026 Online Qualifier: EMEA
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 19 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (19 matchs)
✅ Esports World Cup 2026 Online Qualifier: EMEA: 19 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 330 matchs
📊 Filtré par équipe: Galions (55 games)

✅ Page HTML créée: drafts_LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier_EMEA_Galions.html
Total de drafts: 55

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
4,LFL/2026 Season/Invitational_Day 1_5_1,26.1,Galions,Caldya Esport,1,,Poppy,Malphite,Orianna,Alistar,...,Ryze,Mid,Vi,Jungle,K'Sante,Top,Miss Fortune,Bot,Nautilus,Support
10,LFL/2026 Season/Invitational_Day 3_1_1,26.2,Esprit Shōnen,Galions,2,,Ambessa,Orianna,Nocturne,Alistar,...,Yunara,Bot,Vi,Jungle,Taliyah,Mid,Renekton,Top,Braum,Support
25,LFL/2026 Season/Invitational_Week 1_1_1,26.2,TLN Pirates,Galions,2,,Malphite,Jarvan IV,Varus,Corki,...,Ambessa,Top,Azir,Mid,Pantheon,Jungle,Lucian,Bot,Milio,Support
33,LFL/2026 Season/Invitational_Week 1_9_1,26.2,ZYB Esport,Galions,2,,Ambessa,Orianna,Yone,K'Sante,...,Yunara,Bot,Jarvan IV,Jungle,Taliyah,Mid,Neeko,Support,Gnar,Top
37,LFL/2026 Season/Invitational_Week 1_13_1,26.2,Joblife,Galions,2,,Akali,Varus,Pantheon,Gnar,...,Ambessa,Jungle,Yunara,Bot,Nautilus,Support,Aurora,Top,Ahri,Mid
42,LFL/2026 Season/Invitational_Week 2_3_1,26.3,Solary,Galions,1,,Ambessa,Yunara,Orianna,Corki,...,Sejuani,Jungle,Yone,Mid,Aurora,Top,Lucian,Bot,Nautilus,Support
47,LFL/2026 Season/Invitational_Week 2_8_1,26.3,Galions,Lille Esport,1,,Ahri,Zoe,Rumble,Nautilus,...,Jarvan IV,Jungle,Sion,Top,Syndra,Mid,Rell,Support,Xayah,Bot
53,LFL/2026 Season/Invitational_Week 2_14_1,26.3,Galions,Skillcamp,1,,Rumble,Ambessa,Ryze,Nautilus,...,Taliyah,Mid,Jarvan IV,Jungle,Corki,Bot,Jax,Top,Nami,Support
57,LFL/2026 Season/Invitational_Week 2_18_1,26.3,Galions,Vitality.Bee,2,,Fiora,Rumble,Ambessa,Alistar,...,Varus,Bot,Orianna,Mid,Naafiri,Jungle,Renekton,Top,Rell,Support
60,LFL/2026 Season/Invitational_Week 3_1_1,26.3,Galions,BK ROG Esports,1,,Syndra,Ambessa,Varus,Nautilus,...,Azir,Mid,Yunara,Bot,Dr. Mundo,Jungle,Rakan,Support,Aatrox,Top
68,LFL/2026 Season/Invitational_Week 3_9_1,26.3,French Flair,Galions,1,,Jarvan IV,Ambessa,Yunara,Ezreal,...,Sion,Top,Ahri,Mid,Pantheon,Jungle,Corki,Bot,Renata Glasc,Support
71,LFL/2026 Season/Invitational_Tiebreakers_2_1,26.3,French Flair,Galions,2,,Jarvan IV,Yunara,Ambessa,Nami,...,Orianna,Mid,Corki,Bot,Gwen,Top,Nocturne,Jungle,Neeko,Support
72,LFL/2026 Season/Invitational_Tiebreakers_3_1,26.3,Joblife,Galions,2,,Varus,Ambessa,Sion,Neeko,...,Ornn,Top,Corki,Bot,Taliyah,Mid,Aatrox,Jungle,Nami,Support
81,LFL/2026 Season/Invitational_Round 2_1_1,26.4,Galions,Solary,2,,Varus,Ambessa,Xin Zhao,Rumble,...,Taliyah,Mid,Corki,Bot,Vi,Jungle,Nami,Support,Gwen,Top
82,LFL/2026 Season/Invitational_Round 2_1_2,26.4,Solary,Galions,2,,Ambessa,Nautilus,Sion,Neeko,...,Varus,Bot,Jarvan IV,Jungle,Ornn,Top,Alistar,Support,Aurora,Mid
83,LFL/2026 Season/Invitational_Round 2_1_3,26.4,Galions,Solary,2,,Ambessa,Nautilus,Xin Zhao,Braum,...,Anivia,Mid,Pantheon,Jungle,Sion,Top,Aphelios,Bot,Leona,Support
84,LFL/2026 Season/Invitational_Round 2_1_4,26.4,Solary,Galions,1,,Neeko,Braum,Ambessa,Lucian,...,Mel,Mid,Aatrox,Jungle,Jayce,Top,Rakan,Support,Xayah,Bot
89,LFL/2026 Season/Invitational_Round 3_1_1,26.4,Galions,French Flair,2,,Dr. Mundo,Azir,Jarvan IV,Bard,...,Xin Zhao,Jungle,Aurora,Mid,Sion,Top,Nautilus,Support,Ezreal,Bot
90,LFL/2026 Season/Invitational_Round 3_1_2,26.4,Galions,French Flair,1,,Dr. Mundo,Azir,Corki,Bard,...,Aatrox,Jungle,LeBlanc,Mid,Ambessa,Top,Zeri,Bot,Lulu,Support
91,LFL/2026 Season/Invitational_Round 3_1_3,26.4,French Flair,Galions,2,,Neeko,Nami,Orianna,Gnar,...,Jhin,Bot,Pantheon,Jungle,Bard,Support,Yorick,Top,Syndra,Mid
92,LFL/2026 Season/Invitational_Round 3_1_4,26.4,French Flair,Galions,1,,Caitlyn,Nami,Rumble,Ornn,...,Lucian,Bot,Milio,Support,Akali,Mid,Skarner,Jungle,Malphite,Top
93,LFL/2026 Season/Invitational_Round 3_1_5,26.4,Galions,French Flair,1,,Sylas,Azir,Dr. Mundo,Alistar,...,Kalista,Bot,Nocturne,Jungle,Mel,Mid,Karma,Support,Olaf,Top
94,LFL/2026 Season/Invitational_Finals_1_1,26.4,Galions,Solary,2,,Azir,Nautilus,Renekton,Ryze,...,Corki,Bot,Vi,Jungle,Pyke,Support,Ahri,Mid,Gnar,Top
95,LFL/2026 Season/Invitational_Finals_1_2,26.4,Solary,Galions,1,,Ambessa,Neeko,Varus,Nautilus,...,Ornn,Top,Pantheon,Jungle,Taliyah,Mid,Ezreal,Bot,Nami,Support
96,LFL/2026 Season/Invitational_Finals_1_3,26.4,Galions,Solary,2,,Azir,Jhin,Sion,Xayah,...,Syndra,Mid,Dr. Mundo,Jungle,Vayne,Top,Jinx,Bot,Rell,Support
100,LFL/2026 Season/Spring Split_Week 1_4_1,26.7,Solary,Galions,2,,Ambessa,Nautilus,Karma,Gnar,...,Ezreal,Bot,Xin Zhao,Jungle,Leona,Support,LeBlanc,Mid,Jayce,Top
106,LFL/2026 Season/Spring Split_Week 1_10_1,26.7,Ici Japon Corp. Esport,Galions,1,,Nautilus,Ezreal,Seraphine,Ambessa,...,Corki,Bot,Xin Zhao,Jungle,Nami,Support,LeBlanc,Mid,Gnar,Top
111,LFL/2026 Season/Spring Split_Week 1_15_1,26.7,Galions,Vitality.Bee,2,,Rumble,Nautilus,Ashe,Lulu,...,Yunara,Bot,Pantheon,Jungle,Fiora,Top,Zoe,Mid,Rell,Support
114,LFL/2026 Season/Spring Split_Week 2_3_1,26.7,Galions,ZYB Esport,1,,Nautilus,Kalista,Anivia,Bard,...,Rumble,Top,Galio,Mid,Caitlyn,Bot,Neeko,Support,Xin Zhao,Jungle
118,LFL/2026 Season/Spring Split_Week 2_7_1,26.7,Galions,Skillcamp,1,,Nautilus,Jarvan IV,Anivia,Rumble,...,Bard,Support,Ezreal,Bot,Nocturne,Jungle,Mel,Mid,Gnar,Top
123,LFL/2026 Season/Spring Split_Week 2_12_1,26.7,Galions,TLN Pirates,2,,Caitlyn,Nautilus,Pantheon,Sion,...,Karma,Support,Xin Zhao,Jungle,Yunara,Bot,Ahri,Mid,Rumble,Top
130,LFL/2026 Season/Spring Split_Week 3_4_1,26.8,Galions,Joblife,1,,Karma,Nautilus,Ahri,Aurora,...,Ashe,Bot,Xin Zhao,Jungle,Lulu,Support,Azir,Mid,Ambessa,Top
133,LFL/2026 Season/Spring Split_Week 3_7_1,26.8,Galions,Esprit Shōnen,1,,Varus,Nautilus,Anivia,Ahri,...,Ezreal,Bot,Pantheon,Jungle,Bard,Support,Azir,Mid,K'Sante,Top
155,EMEA Masters/2026 Season/Winter_Groups Day 1_5_1,26.5,Vantex Esports,Galions,2,,Varus,Yunara,Ambessa,Corki,...,Ornn,Top,Vi,Jungle,Ahri,Mid,Kai'Sa,Bot,Rell,Support
158,EMEA Masters/2026 Season/Winter_Groups Day 1_5_2,26.5,Galions,Vantex Esports,1,,Caitlyn,Ambessa,Azir,Naafiri,...,Viktor,Mid,Varus,Bot,Leona,Support,Aatrox,Jungle,Garen,Top
191,EMEA Masters/2026 Season/Winter_Groups Day 3_5_1,26.5,UCAM Esports,Galions,2,,Yunara,Corki,Renekton,Bard,...,Ryze,Mid,Zaahen,Top,Aatrox,Jungle,Neeko,Support,Xayah,Bot
194,EMEA Masters/2026 Season/Winter_Groups Day 3_5_2,26.5,Galions,UCAM Esports,1,,Rumble,Nocturne,Wukong,Gnar,...,Galio,Mid,Yunara,Bot,Trundle,Jungle,Jax,Top,Pyke,Support
228,EMEA Masters/2026 Season/Winter_Groups Day 5_4_1,26.5,UCAM Esports,Galions,2,,Neeko,Ryze,Renekton,Braum,...,Zaahen,Top,Yunara,Bot,Ahri,Mid,Pantheon,Jungle,Renata Glasc,Support
230,EMEA Masters/2026 Season/Winter_Groups Day 5_4_2,26.5,Galions,UCAM Esports,2,,Nocturne,Rumble,Jarvan IV,Lulu,...,Xin Zhao,Jungle,Viktor,Mid,Dr. Mundo,Top,Kalista,Bot,Rakan,Support
234,EMEA Masters/2026 Season/Winter_Groups Day 5_4_3,26.5,UCAM Esports,Galions,2,,Neeko,Akali,Gwen,Karma,...,Ryze,Mid,Aatrox,Jungle,Gnar,Top,Varus,Bot,Bard,Support
261,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Eintracht Spandau,1,,Rumble,Nautilus,Ezreal,Sion,...,Azir,Mid,Nami,Support,Corki,Bot,Xin Zhao,Jungle,Gnar,Top
262,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Eintracht Spandau,Galions,2,,Ashe,Karma,Vi,Aurora,...,Ambessa,Top,Kai'Sa,Bot,Leona,Support,Ahri,Mid,Qiyana,Jungle
267,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Ashe,Vi,LeBlanc,...,Ezreal,Bot,Pantheon,Jungle,Braum,Support,Mel,Mid,K'Sante,Top
270,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Vi,LeBlanc,Ornn,...,Wukong,Jungle,Corki,Bot,Aurora,Mid,Neeko,Support,Gnar,Top
272,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,French Flair,1,,Dr. Mundo,Azir,Karma,Anivia,...,Varus,Bot,Jarvan IV,Jungle,Nautilus,Support,Aurora,Mid,Volibear,Top
275,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,French Flair,Galions,2,,Gwen,Wukong,Yunara,Vi,...,Ashe,Bot,Seraphine,Support,Ahri,Mid,Aatrox,Jungle,Renekton,Top
288,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Solary,Galions,2,,Ambessa,Karma,Vi,Ahri,...,Ezreal,Bot,Xin Zhao,Jungle,Nautilus,Support,Taliyah,Mid,Ornn,Top
289,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,2,,Azir,Ahri,Jarvan IV,Aurora,...,Ashe,Bot,Seraphine,Support,Pantheon,Jungle,Viktor,Mid,K'Sante,Top
291,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Karma,Corki,Dr. Mundo,...,Lucian,Bot,Nami,Support,Cassiopeia,Mid,Skarner,Jungle,Yorick,Top
293,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Ahri,Karma,Alistar,...,Kai'Sa,Bot,Aurora,Mid,Sion,Top,Rell,Support,Viego,Jungle
308,EMEA Masters/2026 Season/Winter_Finals_1_1,26.8,Galions,Solary,2,,Rumble,Xin Zhao,Ryze,Vayne,...,Pantheon,Jungle,Caitlyn,Bot,Rell,Support,Ahri,Mid,K'Sante,Top
309,EMEA Masters/2026 Season/Winter_Finals_1_2,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Xin Zhao,Ornn,...,Nocturne,Jungle,Nami,Support,Lucian,Bot,LeBlanc,Mid,Ambessa,Top
310,EMEA Masters/2026 Season/Winter_Finals_1_3,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Neeko,Rakan,...,Varus,Bot,Vi,Jungle,Taliyah,Mid,Leona,Support,Gwen,Top
311,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Natus Vincere,Galions,1,,Nautilus,Jarvan IV,Ryze,Nocturne,...,Ashe,Bot,Seraphine,Support,Aurora,Mid,Aatrox,Jungle,Gnar,Top
313,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Galions,Natus Vincere,2,,Nautilus,Karma,Varus,K'Sante,...,Yunara,Bot,Lulu,Support,Anivia,Mid,Ornn,Top,Graves,Jungle

---
## 2 · Pick order stats
Pick rate + winrate per role per pick slot (P1 / P2-P3 / P4-P5 for blue, etc.).

In [8]:
analyze_pick_order(
    site,
    tournaments     = TOURNAMENTS,
    output_filename = f"pick_order_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = 500,
)

============================================================
🔍 Traitement du tournoi: LFL 2026 Invitational
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 97 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (97 matchs)
✅ LFL 2026 Invitational: 97 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LFL 2026 Spring
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 40 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (40 matchs)
✅ LFL 2026 Spring: 40 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: EM 2026 Winter
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 174 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (174 matchs)
✅ EM 2026 Winter: 174 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: Esports World Cup 2026 Online Qualifier: EMEA
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 19 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (19 matchs)
✅ Esports World Cup 2026 Online Qualifier: EMEA: 19 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 330 matchs
📊 Filtré par équipe: Galions (55 games)

✅ Page HTML créée: pick_order_LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier_EMEA_Galions.html
Total de games: 55

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
4,LFL/2026 Season/Invitational_Day 1_5_1,26.1,Galions,Caldya Esport,1,,Poppy,Malphite,Orianna,Alistar,...,Ryze,Mid,Vi,Jungle,K'Sante,Top,Miss Fortune,Bot,Nautilus,Support
10,LFL/2026 Season/Invitational_Day 3_1_1,26.2,Esprit Shōnen,Galions,2,,Ambessa,Orianna,Nocturne,Alistar,...,Yunara,Bot,Vi,Jungle,Taliyah,Mid,Renekton,Top,Braum,Support
25,LFL/2026 Season/Invitational_Week 1_1_1,26.2,TLN Pirates,Galions,2,,Malphite,Jarvan IV,Varus,Corki,...,Ambessa,Top,Azir,Mid,Pantheon,Jungle,Lucian,Bot,Milio,Support
33,LFL/2026 Season/Invitational_Week 1_9_1,26.2,ZYB Esport,Galions,2,,Ambessa,Orianna,Yone,K'Sante,...,Yunara,Bot,Jarvan IV,Jungle,Taliyah,Mid,Neeko,Support,Gnar,Top
37,LFL/2026 Season/Invitational_Week 1_13_1,26.2,Joblife,Galions,2,,Akali,Varus,Pantheon,Gnar,...,Ambessa,Jungle,Yunara,Bot,Nautilus,Support,Aurora,Top,Ahri,Mid
42,LFL/2026 Season/Invitational_Week 2_3_1,26.3,Solary,Galions,1,,Ambessa,Yunara,Orianna,Corki,...,Sejuani,Jungle,Yone,Mid,Aurora,Top,Lucian,Bot,Nautilus,Support
47,LFL/2026 Season/Invitational_Week 2_8_1,26.3,Galions,Lille Esport,1,,Ahri,Zoe,Rumble,Nautilus,...,Jarvan IV,Jungle,Sion,Top,Syndra,Mid,Rell,Support,Xayah,Bot
53,LFL/2026 Season/Invitational_Week 2_14_1,26.3,Galions,Skillcamp,1,,Rumble,Ambessa,Ryze,Nautilus,...,Taliyah,Mid,Jarvan IV,Jungle,Corki,Bot,Jax,Top,Nami,Support
57,LFL/2026 Season/Invitational_Week 2_18_1,26.3,Galions,Vitality.Bee,2,,Fiora,Rumble,Ambessa,Alistar,...,Varus,Bot,Orianna,Mid,Naafiri,Jungle,Renekton,Top,Rell,Support
60,LFL/2026 Season/Invitational_Week 3_1_1,26.3,Galions,BK ROG Esports,1,,Syndra,Ambessa,Varus,Nautilus,...,Azir,Mid,Yunara,Bot,Dr. Mundo,Jungle,Rakan,Support,Aatrox,Top
68,LFL/2026 Season/Invitational_Week 3_9_1,26.3,French Flair,Galions,1,,Jarvan IV,Ambessa,Yunara,Ezreal,...,Sion,Top,Ahri,Mid,Pantheon,Jungle,Corki,Bot,Renata Glasc,Support
71,LFL/2026 Season/Invitational_Tiebreakers_2_1,26.3,French Flair,Galions,2,,Jarvan IV,Yunara,Ambessa,Nami,...,Orianna,Mid,Corki,Bot,Gwen,Top,Nocturne,Jungle,Neeko,Support
72,LFL/2026 Season/Invitational_Tiebreakers_3_1,26.3,Joblife,Galions,2,,Varus,Ambessa,Sion,Neeko,...,Ornn,Top,Corki,Bot,Taliyah,Mid,Aatrox,Jungle,Nami,Support
81,LFL/2026 Season/Invitational_Round 2_1_1,26.4,Galions,Solary,2,,Varus,Ambessa,Xin Zhao,Rumble,...,Taliyah,Mid,Corki,Bot,Vi,Jungle,Nami,Support,Gwen,Top
82,LFL/2026 Season/Invitational_Round 2_1_2,26.4,Solary,Galions,2,,Ambessa,Nautilus,Sion,Neeko,...,Varus,Bot,Jarvan IV,Jungle,Ornn,Top,Alistar,Support,Aurora,Mid
83,LFL/2026 Season/Invitational_Round 2_1_3,26.4,Galions,Solary,2,,Ambessa,Nautilus,Xin Zhao,Braum,...,Anivia,Mid,Pantheon,Jungle,Sion,Top,Aphelios,Bot,Leona,Support
84,LFL/2026 Season/Invitational_Round 2_1_4,26.4,Solary,Galions,1,,Neeko,Braum,Ambessa,Lucian,...,Mel,Mid,Aatrox,Jungle,Jayce,Top,Rakan,Support,Xayah,Bot
89,LFL/2026 Season/Invitational_Round 3_1_1,26.4,Galions,French Flair,2,,Dr. Mundo,Azir,Jarvan IV,Bard,...,Xin Zhao,Jungle,Aurora,Mid,Sion,Top,Nautilus,Support,Ezreal,Bot
90,LFL/2026 Season/Invitational_Round 3_1_2,26.4,Galions,French Flair,1,,Dr. Mundo,Azir,Corki,Bard,...,Aatrox,Jungle,LeBlanc,Mid,Ambessa,Top,Zeri,Bot,Lulu,Support
91,LFL/2026 Season/Invitational_Round 3_1_3,26.4,French Flair,Galions,2,,Neeko,Nami,Orianna,Gnar,...,Jhin,Bot,Pantheon,Jungle,Bard,Support,Yorick,Top,Syndra,Mid
92,LFL/2026 Season/Invitational_Round 3_1_4,26.4,French Flair,Galions,1,,Caitlyn,Nami,Rumble,Ornn,...,Lucian,Bot,Milio,Support,Akali,Mid,Skarner,Jungle,Malphite,Top
93,LFL/2026 Season/Invitational_Round 3_1_5,26.4,Galions,French Flair,1,,Sylas,Azir,Dr. Mundo,Alistar,...,Kalista,Bot,Nocturne,Jungle,Mel,Mid,Karma,Support,Olaf,Top
94,LFL/2026 Season/Invitational_Finals_1_1,26.4,Galions,Solary,2,,Azir,Nautilus,Renekton,Ryze,...,Corki,Bot,Vi,Jungle,Pyke,Support,Ahri,Mid,Gnar,Top
95,LFL/2026 Season/Invitational_Finals_1_2,26.4,Solary,Galions,1,,Ambessa,Neeko,Varus,Nautilus,...,Ornn,Top,Pantheon,Jungle,Taliyah,Mid,Ezreal,Bot,Nami,Support
96,LFL/2026 Season/Invitational_Finals_1_3,26.4,Galions,Solary,2,,Azir,Jhin,Sion,Xayah,...,Syndra,Mid,Dr. Mundo,Jungle,Vayne,Top,Jinx,Bot,Rell,Support
100,LFL/2026 Season/Spring Split_Week 1_4_1,26.7,Solary,Galions,2,,Ambessa,Nautilus,Karma,Gnar,...,Ezreal,Bot,Xin Zhao,Jungle,Leona,Support,LeBlanc,Mid,Jayce,Top
106,LFL/2026 Season/Spring Split_Week 1_10_1,26.7,Ici Japon Corp. Esport,Galions,1,,Nautilus,Ezreal,Seraphine,Ambessa,...,Corki,Bot,Xin Zhao,Jungle,Nami,Support,LeBlanc,Mid,Gnar,Top
111,LFL/2026 Season/Spring Split_Week 1_15_1,26.7,Galions,Vitality.Bee,2,,Rumble,Nautilus,Ashe,Lulu,...,Yunara,Bot,Pantheon,Jungle,Fiora,Top,Zoe,Mid,Rell,Support
114,LFL/2026 Season/Spring Split_Week 2_3_1,26.7,Galions,ZYB Esport,1,,Nautilus,Kalista,Anivia,Bard,...,Rumble,Top,Galio,Mid,Caitlyn,Bot,Neeko,Support,Xin Zhao,Jungle
118,LFL/2026 Season/Spring Split_Week 2_7_1,26.7,Galions,Skillcamp,1,,Nautilus,Jarvan IV,Anivia,Rumble,...,Bard,Support,Ezreal,Bot,Nocturne,Jungle,Mel,Mid,Gnar,Top
123,LFL/2026 Season/Spring Split_Week 2_12_1,26.7,Galions,TLN Pirates,2,,Caitlyn,Nautilus,Pantheon,Sion,...,Karma,Support,Xin Zhao,Jungle,Yunara,Bot,Ahri,Mid,Rumble,Top
130,LFL/2026 Season/Spring Split_Week 3_4_1,26.8,Galions,Joblife,1,,Karma,Nautilus,Ahri,Aurora,...,Ashe,Bot,Xin Zhao,Jungle,Lulu,Support,Azir,Mid,Ambessa,Top
133,LFL/2026 Season/Spring Split_Week 3_7_1,26.8,Galions,Esprit Shōnen,1,,Varus,Nautilus,Anivia,Ahri,...,Ezreal,Bot,Pantheon,Jungle,Bard,Support,Azir,Mid,K'Sante,Top
155,EMEA Masters/2026 Season/Winter_Groups Day 1_5_1,26.5,Vantex Esports,Galions,2,,Varus,Yunara,Ambessa,Corki,...,Ornn,Top,Vi,Jungle,Ahri,Mid,Kai'Sa,Bot,Rell,Support
158,EMEA Masters/2026 Season/Winter_Groups Day 1_5_2,26.5,Galions,Vantex Esports,1,,Caitlyn,Ambessa,Azir,Naafiri,...,Viktor,Mid,Varus,Bot,Leona,Support,Aatrox,Jungle,Garen,Top
191,EMEA Masters/2026 Season/Winter_Groups Day 3_5_1,26.5,UCAM Esports,Galions,2,,Yunara,Corki,Renekton,Bard,...,Ryze,Mid,Zaahen,Top,Aatrox,Jungle,Neeko,Support,Xayah,Bot
194,EMEA Masters/2026 Season/Winter_Groups Day 3_5_2,26.5,Galions,UCAM Esports,1,,Rumble,Nocturne,Wukong,Gnar,...,Galio,Mid,Yunara,Bot,Trundle,Jungle,Jax,Top,Pyke,Support
228,EMEA Masters/2026 Season/Winter_Groups Day 5_4_1,26.5,UCAM Esports,Galions,2,,Neeko,Ryze,Renekton,Braum,...,Zaahen,Top,Yunara,Bot,Ahri,Mid,Pantheon,Jungle,Renata Glasc,Support
230,EMEA Masters/2026 Season/Winter_Groups Day 5_4_2,26.5,Galions,UCAM Esports,2,,Nocturne,Rumble,Jarvan IV,Lulu,...,Xin Zhao,Jungle,Viktor,Mid,Dr. Mundo,Top,Kalista,Bot,Rakan,Support
234,EMEA Masters/2026 Season/Winter_Groups Day 5_4_3,26.5,UCAM Esports,Galions,2,,Neeko,Akali,Gwen,Karma,...,Ryze,Mid,Aatrox,Jungle,Gnar,Top,Varus,Bot,Bard,Support
261,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Eintracht Spandau,1,,Rumble,Nautilus,Ezreal,Sion,...,Azir,Mid,Nami,Support,Corki,Bot,Xin Zhao,Jungle,Gnar,Top
262,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Eintracht Spandau,Galions,2,,Ashe,Karma,Vi,Aurora,...,Ambessa,Top,Kai'Sa,Bot,Leona,Support,Ahri,Mid,Qiyana,Jungle
267,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Ashe,Vi,LeBlanc,...,Ezreal,Bot,Pantheon,Jungle,Braum,Support,Mel,Mid,K'Sante,Top
270,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Vi,LeBlanc,Ornn,...,Wukong,Jungle,Corki,Bot,Aurora,Mid,Neeko,Support,Gnar,Top
272,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,French Flair,1,,Dr. Mundo,Azir,Karma,Anivia,...,Varus,Bot,Jarvan IV,Jungle,Nautilus,Support,Aurora,Mid,Volibear,Top
275,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,French Flair,Galions,2,,Gwen,Wukong,Yunara,Vi,...,Ashe,Bot,Seraphine,Support,Ahri,Mid,Aatrox,Jungle,Renekton,Top
288,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Solary,Galions,2,,Ambessa,Karma,Vi,Ahri,...,Ezreal,Bot,Xin Zhao,Jungle,Nautilus,Support,Taliyah,Mid,Ornn,Top
289,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,2,,Azir,Ahri,Jarvan IV,Aurora,...,Ashe,Bot,Seraphine,Support,Pantheon,Jungle,Viktor,Mid,K'Sante,Top
291,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Karma,Corki,Dr. Mundo,...,Lucian,Bot,Nami,Support,Cassiopeia,Mid,Skarner,Jungle,Yorick,Top
293,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Ahri,Karma,Alistar,...,Kai'Sa,Bot,Aurora,Mid,Sion,Top,Rell,Support,Viego,Jungle
308,EMEA Masters/2026 Season/Winter_Finals_1_1,26.8,Galions,Solary,2,,Rumble,Xin Zhao,Ryze,Vayne,...,Pantheon,Jungle,Caitlyn,Bot,Rell,Support,Ahri,Mid,K'Sante,Top
309,EMEA Masters/2026 Season/Winter_Finals_1_2,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Xin Zhao,Ornn,...,Nocturne,Jungle,Nami,Support,Lucian,Bot,LeBlanc,Mid,Ambessa,Top
310,EMEA Masters/2026 Season/Winter_Finals_1_3,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Neeko,Rakan,...,Varus,Bot,Vi,Jungle,Taliyah,Mid,Leona,Support,Gwen,Top
311,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Natus Vincere,Galions,1,,Nautilus,Jarvan IV,Ryze,Nocturne,...,Ashe,Bot,Seraphine,Support,Aurora,Mid,Aatrox,Jungle,Gnar,Top
313,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Galions,Natus Vincere,2,,Nautilus,Karma,Varus,K'Sante,...,Yunara,Bot,Lulu,Support,Anivia,Mid,Ornn,Top,Graves,Jungle

---
## 3 · Champion stats by role
Games played, W-L, and winrate for every champion per role.

In [9]:
analyze_champions(
    site,
    tournaments     = TOURNAMENTS,
    output_filename = f"champions_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = 500,
)

============================================================
🔍 Traitement du tournoi: LFL 2026 Invitational
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 97 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (97 matchs)
✅ LFL 2026 Invitational: 97 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LFL 2026 Spring
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 40 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (40 matchs)
✅ LFL 2026 Spring: 40 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: EM 2026 Winter
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 174 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (174 matchs)
✅ EM 2026 Winter: 174 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: Esports World Cup 2026 Online Qualifier: EMEA
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 19 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (19 matchs)
✅ Esports World Cup 2026 Online Qualifier: EMEA: 19 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 330 matchs
📊 Filtré par équipe: Galions (55 games)

✅ Page web créée: champions_LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier_EMEA_Galions.html
Titre: Champions Stats - Galions (55 Games)
Total de games analysées: 55

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
4,LFL/2026 Season/Invitational_Day 1_5_1,26.1,Galions,Caldya Esport,1,,Poppy,Malphite,Orianna,Alistar,...,Ryze,Mid,Vi,Jungle,K'Sante,Top,Miss Fortune,Bot,Nautilus,Support
10,LFL/2026 Season/Invitational_Day 3_1_1,26.2,Esprit Shōnen,Galions,2,,Ambessa,Orianna,Nocturne,Alistar,...,Yunara,Bot,Vi,Jungle,Taliyah,Mid,Renekton,Top,Braum,Support
25,LFL/2026 Season/Invitational_Week 1_1_1,26.2,TLN Pirates,Galions,2,,Malphite,Jarvan IV,Varus,Corki,...,Ambessa,Top,Azir,Mid,Pantheon,Jungle,Lucian,Bot,Milio,Support
33,LFL/2026 Season/Invitational_Week 1_9_1,26.2,ZYB Esport,Galions,2,,Ambessa,Orianna,Yone,K'Sante,...,Yunara,Bot,Jarvan IV,Jungle,Taliyah,Mid,Neeko,Support,Gnar,Top
37,LFL/2026 Season/Invitational_Week 1_13_1,26.2,Joblife,Galions,2,,Akali,Varus,Pantheon,Gnar,...,Ambessa,Jungle,Yunara,Bot,Nautilus,Support,Aurora,Top,Ahri,Mid
42,LFL/2026 Season/Invitational_Week 2_3_1,26.3,Solary,Galions,1,,Ambessa,Yunara,Orianna,Corki,...,Sejuani,Jungle,Yone,Mid,Aurora,Top,Lucian,Bot,Nautilus,Support
47,LFL/2026 Season/Invitational_Week 2_8_1,26.3,Galions,Lille Esport,1,,Ahri,Zoe,Rumble,Nautilus,...,Jarvan IV,Jungle,Sion,Top,Syndra,Mid,Rell,Support,Xayah,Bot
53,LFL/2026 Season/Invitational_Week 2_14_1,26.3,Galions,Skillcamp,1,,Rumble,Ambessa,Ryze,Nautilus,...,Taliyah,Mid,Jarvan IV,Jungle,Corki,Bot,Jax,Top,Nami,Support
57,LFL/2026 Season/Invitational_Week 2_18_1,26.3,Galions,Vitality.Bee,2,,Fiora,Rumble,Ambessa,Alistar,...,Varus,Bot,Orianna,Mid,Naafiri,Jungle,Renekton,Top,Rell,Support
60,LFL/2026 Season/Invitational_Week 3_1_1,26.3,Galions,BK ROG Esports,1,,Syndra,Ambessa,Varus,Nautilus,...,Azir,Mid,Yunara,Bot,Dr. Mundo,Jungle,Rakan,Support,Aatrox,Top
68,LFL/2026 Season/Invitational_Week 3_9_1,26.3,French Flair,Galions,1,,Jarvan IV,Ambessa,Yunara,Ezreal,...,Sion,Top,Ahri,Mid,Pantheon,Jungle,Corki,Bot,Renata Glasc,Support
71,LFL/2026 Season/Invitational_Tiebreakers_2_1,26.3,French Flair,Galions,2,,Jarvan IV,Yunara,Ambessa,Nami,...,Orianna,Mid,Corki,Bot,Gwen,Top,Nocturne,Jungle,Neeko,Support
72,LFL/2026 Season/Invitational_Tiebreakers_3_1,26.3,Joblife,Galions,2,,Varus,Ambessa,Sion,Neeko,...,Ornn,Top,Corki,Bot,Taliyah,Mid,Aatrox,Jungle,Nami,Support
81,LFL/2026 Season/Invitational_Round 2_1_1,26.4,Galions,Solary,2,,Varus,Ambessa,Xin Zhao,Rumble,...,Taliyah,Mid,Corki,Bot,Vi,Jungle,Nami,Support,Gwen,Top
82,LFL/2026 Season/Invitational_Round 2_1_2,26.4,Solary,Galions,2,,Ambessa,Nautilus,Sion,Neeko,...,Varus,Bot,Jarvan IV,Jungle,Ornn,Top,Alistar,Support,Aurora,Mid
83,LFL/2026 Season/Invitational_Round 2_1_3,26.4,Galions,Solary,2,,Ambessa,Nautilus,Xin Zhao,Braum,...,Anivia,Mid,Pantheon,Jungle,Sion,Top,Aphelios,Bot,Leona,Support
84,LFL/2026 Season/Invitational_Round 2_1_4,26.4,Solary,Galions,1,,Neeko,Braum,Ambessa,Lucian,...,Mel,Mid,Aatrox,Jungle,Jayce,Top,Rakan,Support,Xayah,Bot
89,LFL/2026 Season/Invitational_Round 3_1_1,26.4,Galions,French Flair,2,,Dr. Mundo,Azir,Jarvan IV,Bard,...,Xin Zhao,Jungle,Aurora,Mid,Sion,Top,Nautilus,Support,Ezreal,Bot
90,LFL/2026 Season/Invitational_Round 3_1_2,26.4,Galions,French Flair,1,,Dr. Mundo,Azir,Corki,Bard,...,Aatrox,Jungle,LeBlanc,Mid,Ambessa,Top,Zeri,Bot,Lulu,Support
91,LFL/2026 Season/Invitational_Round 3_1_3,26.4,French Flair,Galions,2,,Neeko,Nami,Orianna,Gnar,...,Jhin,Bot,Pantheon,Jungle,Bard,Support,Yorick,Top,Syndra,Mid
92,LFL/2026 Season/Invitational_Round 3_1_4,26.4,French Flair,Galions,1,,Caitlyn,Nami,Rumble,Ornn,...,Lucian,Bot,Milio,Support,Akali,Mid,Skarner,Jungle,Malphite,Top
93,LFL/2026 Season/Invitational_Round 3_1_5,26.4,Galions,French Flair,1,,Sylas,Azir,Dr. Mundo,Alistar,...,Kalista,Bot,Nocturne,Jungle,Mel,Mid,Karma,Support,Olaf,Top
94,LFL/2026 Season/Invitational_Finals_1_1,26.4,Galions,Solary,2,,Azir,Nautilus,Renekton,Ryze,...,Corki,Bot,Vi,Jungle,Pyke,Support,Ahri,Mid,Gnar,Top
95,LFL/2026 Season/Invitational_Finals_1_2,26.4,Solary,Galions,1,,Ambessa,Neeko,Varus,Nautilus,...,Ornn,Top,Pantheon,Jungle,Taliyah,Mid,Ezreal,Bot,Nami,Support
96,LFL/2026 Season/Invitational_Finals_1_3,26.4,Galions,Solary,2,,Azir,Jhin,Sion,Xayah,...,Syndra,Mid,Dr. Mundo,Jungle,Vayne,Top,Jinx,Bot,Rell,Support
100,LFL/2026 Season/Spring Split_Week 1_4_1,26.7,Solary,Galions,2,,Ambessa,Nautilus,Karma,Gnar,...,Ezreal,Bot,Xin Zhao,Jungle,Leona,Support,LeBlanc,Mid,Jayce,Top
106,LFL/2026 Season/Spring Split_Week 1_10_1,26.7,Ici Japon Corp. Esport,Galions,1,,Nautilus,Ezreal,Seraphine,Ambessa,...,Corki,Bot,Xin Zhao,Jungle,Nami,Support,LeBlanc,Mid,Gnar,Top
111,LFL/2026 Season/Spring Split_Week 1_15_1,26.7,Galions,Vitality.Bee,2,,Rumble,Nautilus,Ashe,Lulu,...,Yunara,Bot,Pantheon,Jungle,Fiora,Top,Zoe,Mid,Rell,Support
114,LFL/2026 Season/Spring Split_Week 2_3_1,26.7,Galions,ZYB Esport,1,,Nautilus,Kalista,Anivia,Bard,...,Rumble,Top,Galio,Mid,Caitlyn,Bot,Neeko,Support,Xin Zhao,Jungle
118,LFL/2026 Season/Spring Split_Week 2_7_1,26.7,Galions,Skillcamp,1,,Nautilus,Jarvan IV,Anivia,Rumble,...,Bard,Support,Ezreal,Bot,Nocturne,Jungle,Mel,Mid,Gnar,Top
123,LFL/2026 Season/Spring Split_Week 2_12_1,26.7,Galions,TLN Pirates,2,,Caitlyn,Nautilus,Pantheon,Sion,...,Karma,Support,Xin Zhao,Jungle,Yunara,Bot,Ahri,Mid,Rumble,Top
130,LFL/2026 Season/Spring Split_Week 3_4_1,26.8,Galions,Joblife,1,,Karma,Nautilus,Ahri,Aurora,...,Ashe,Bot,Xin Zhao,Jungle,Lulu,Support,Azir,Mid,Ambessa,Top
133,LFL/2026 Season/Spring Split_Week 3_7_1,26.8,Galions,Esprit Shōnen,1,,Varus,Nautilus,Anivia,Ahri,...,Ezreal,Bot,Pantheon,Jungle,Bard,Support,Azir,Mid,K'Sante,Top
155,EMEA Masters/2026 Season/Winter_Groups Day 1_5_1,26.5,Vantex Esports,Galions,2,,Varus,Yunara,Ambessa,Corki,...,Ornn,Top,Vi,Jungle,Ahri,Mid,Kai'Sa,Bot,Rell,Support
158,EMEA Masters/2026 Season/Winter_Groups Day 1_5_2,26.5,Galions,Vantex Esports,1,,Caitlyn,Ambessa,Azir,Naafiri,...,Viktor,Mid,Varus,Bot,Leona,Support,Aatrox,Jungle,Garen,Top
191,EMEA Masters/2026 Season/Winter_Groups Day 3_5_1,26.5,UCAM Esports,Galions,2,,Yunara,Corki,Renekton,Bard,...,Ryze,Mid,Zaahen,Top,Aatrox,Jungle,Neeko,Support,Xayah,Bot
194,EMEA Masters/2026 Season/Winter_Groups Day 3_5_2,26.5,Galions,UCAM Esports,1,,Rumble,Nocturne,Wukong,Gnar,...,Galio,Mid,Yunara,Bot,Trundle,Jungle,Jax,Top,Pyke,Support
228,EMEA Masters/2026 Season/Winter_Groups Day 5_4_1,26.5,UCAM Esports,Galions,2,,Neeko,Ryze,Renekton,Braum,...,Zaahen,Top,Yunara,Bot,Ahri,Mid,Pantheon,Jungle,Renata Glasc,Support
230,EMEA Masters/2026 Season/Winter_Groups Day 5_4_2,26.5,Galions,UCAM Esports,2,,Nocturne,Rumble,Jarvan IV,Lulu,...,Xin Zhao,Jungle,Viktor,Mid,Dr. Mundo,Top,Kalista,Bot,Rakan,Support
234,EMEA Masters/2026 Season/Winter_Groups Day 5_4_3,26.5,UCAM Esports,Galions,2,,Neeko,Akali,Gwen,Karma,...,Ryze,Mid,Aatrox,Jungle,Gnar,Top,Varus,Bot,Bard,Support
261,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Eintracht Spandau,1,,Rumble,Nautilus,Ezreal,Sion,...,Azir,Mid,Nami,Support,Corki,Bot,Xin Zhao,Jungle,Gnar,Top
262,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Eintracht Spandau,Galions,2,,Ashe,Karma,Vi,Aurora,...,Ambessa,Top,Kai'Sa,Bot,Leona,Support,Ahri,Mid,Qiyana,Jungle
267,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Ashe,Vi,LeBlanc,...,Ezreal,Bot,Pantheon,Jungle,Braum,Support,Mel,Mid,K'Sante,Top
270,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Movistar KOI Fénix,Galions,2,,Ambessa,Vi,LeBlanc,Ornn,...,Wukong,Jungle,Corki,Bot,Aurora,Mid,Neeko,Support,Gnar,Top
272,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,French Flair,1,,Dr. Mundo,Azir,Karma,Anivia,...,Varus,Bot,Jarvan IV,Jungle,Nautilus,Support,Aurora,Mid,Volibear,Top
275,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,French Flair,Galions,2,,Gwen,Wukong,Yunara,Vi,...,Ashe,Bot,Seraphine,Support,Ahri,Mid,Aatrox,Jungle,Renekton,Top
288,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Solary,Galions,2,,Ambessa,Karma,Vi,Ahri,...,Ezreal,Bot,Xin Zhao,Jungle,Nautilus,Support,Taliyah,Mid,Ornn,Top
289,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,2,,Azir,Ahri,Jarvan IV,Aurora,...,Ashe,Bot,Seraphine,Support,Pantheon,Jungle,Viktor,Mid,K'Sante,Top
291,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Karma,Corki,Dr. Mundo,...,Lucian,Bot,Nami,Support,Cassiopeia,Mid,Skarner,Jungle,Yorick,Top
293,EMEA Masters/2026 Season/Winter_Playoffs Round...,26.6,Galions,Solary,1,,Azir,Ahri,Karma,Alistar,...,Kai'Sa,Bot,Aurora,Mid,Sion,Top,Rell,Support,Viego,Jungle
308,EMEA Masters/2026 Season/Winter_Finals_1_1,26.8,Galions,Solary,2,,Rumble,Xin Zhao,Ryze,Vayne,...,Pantheon,Jungle,Caitlyn,Bot,Rell,Support,Ahri,Mid,K'Sante,Top
309,EMEA Masters/2026 Season/Winter_Finals_1_2,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Xin Zhao,Ornn,...,Nocturne,Jungle,Nami,Support,Lucian,Bot,LeBlanc,Mid,Ambessa,Top
310,EMEA Masters/2026 Season/Winter_Finals_1_3,26.8,Solary,Galions,1,,Ezreal,Jarvan IV,Neeko,Rakan,...,Varus,Bot,Vi,Jungle,Taliyah,Mid,Leona,Support,Gwen,Top
311,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Natus Vincere,Galions,1,,Nautilus,Jarvan IV,Ryze,Nocturne,...,Ashe,Bot,Seraphine,Support,Aurora,Mid,Aatrox,Jungle,Gnar,Top
313,Esports World Cup 2026/Online Qualifiers/EMEA_...,26.8,Galions,Natus Vincere,2,,Nautilus,Karma,Varus,K'Sante,...,Yunara,Bot,Lulu,Support,Anivia,Mid,Ornn,Top,Graves,Jungle

---
## 4 · Ban analysis
What gets banned when a specific champion (or duo) is picked?

In [9]:
# ── Single champion, any pick position ──────────────────────────────────────
CHAMPION = "Azir"

analyze_bans(
    site,
    tournaments     = TOURNAMENTS,
    champion        = CHAMPION,
    output_filename = f"bans_{CHAMPION}_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = 500,
)

# ── Specific pick slot(s) ────────────────────────────────────────────────────
# CHAMPION = "Corki"
# SLOTS    = ["Team2Pick1", "Team2Pick2"]
# analyze_bans(site, TOURNAMENTS, CHAMPION,
#              pick_moments=SLOTS,
#              output_filename=f"bans_{CHAMPION}_{''.join(SLOTS)}_{SUFFIX}.html",
#              team_filter=TEAM, patches=PATCHES)

# ── Duo (both champs in same team) ───────────────────────────────────────────
# CHAMPION = "Azir"
# DUO      = "Rumble"
# analyze_bans(site, TOURNAMENTS, CHAMPION, champion_duo=DUO,
#              output_filename=f"bans_{CHAMPION}+{DUO}_{SUFFIX}.html",
#              team_filter=TEAM, patches=PATCHES)

============================================================
🔍 Traitement du tournoi: LFL 2026 Invitational
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 97 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (97 matchs)
✅ LFL 2026 Invitational: 97 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LFL 2026 Spring
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 40 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (40 matchs)
✅ LFL 2026 Spring: 40 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: EM 2026 Winter
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 174 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (174 matchs)
✅ EM 2026 Winter: 174 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: Esports World Cup 2026 Online Qualifier: EMEA
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 19 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (19 matchs)
✅ Esports World Cup 2026 Online Qualifier: EMEA: 19 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 330 matchs
📊 Filtré par équipe: Galions (55 games)

================================================================================
📊 ANALYSE DES BANS: AZIR @ ANY POSITION
================================================================================
Tournois: LFL 2026 Invitational, LFL 2026 Spring, EM 2026 Winter, Esports World Cup 2026 Online Qualifier: EMEA
Équipe filtrée: Galions
Games trouvées: 13

✅ Page HTML créée: bans_Azir_LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier:EMEA_Galions.html
Total de games: 13
Ouvre le fichier dans ton navigateur!

✅ Page HTML créée: bans_Azir_LFL2026Invitational-LFL2026Spring-EM2026Winter-EsportsWorldCup2026OnlineQualifier:EMEA_Galions.html
Total de games: 13
Ouvre le fichier dans ton navigateur!

(     Champion  Count Frequency PerGame
 0    Nautilus      9     69.2%    0.69
 1     Ambessa      8     61.5%    0.62
 2       Varus      6     46.2%    0.46
 3      Rumble      5     38.5%    0.38
 4       Karma      3     23.1%    0.23
 5       Corki      2     15.4%    0.15
 6     Orianna      2     15.4%    0.15
 7     Alistar      2     15.4%    0.15
 8        Sion      2     15.4%    0.15
 9       Neeko      2     15.4%    0.15
 10       Gwen      2     15.4%    0.15
 11       Ahri      2     15.4%    0.15
 12   Malphite      1      7.7%    0.08
 13  Jarvan IV      1      7.7%    0.08
 14      Sivir      1      7.7%    0.08
 15       Yone      1      7.7%    0.08
 16    K'Sante      1      7.7%    0.08
 17     Yunara      1      7.7%    0.08
 18       Rell      1      7.7%    0.08
 19       Ryze      1      7.7%    0.08
 20      Fiora      1      7.7%    0.08
 21     Syndra      1      7.7%    0.08
 22       Lulu      1      7.7%    0.08
 23         Vi      1      7.7%    0.08
 24   Xin Zhao      1      7.7%    0.08
 25       Gnar      1      7.7%    0.08
 26     Aurora      1      7.7%    0.08
 27     Anivia      1      7.7%    0.08
 28      Akali      1      7.7%    0.08
 29    Caitlyn      1      7.7%    0.08
 30     Ezreal      1      7.7%    0.08
 31  Dr. Mundo      1      7.7%    0.08,
      Champion  Count Frequency PerGame
 0     Orianna      9     69.2%    0.69
 1       Jayce      4     30.8%    0.31
 2      Yunara      4     30.8%    0.31
 3        Ryze      4     30.8%    0.31
 4     Caitlyn      3     23.1%    0.23
 5    Pantheon      3     23.1%    0.23
 6        Gnar      3     23.1%    0.23
 7     Alistar      2     15.4%    0.15
 8   Dr. Mundo      2     15.4%    0.15
 9       Braum      2     15.4%    0.15
 10       Rell      2     15.4%    0.15
 11    K'Sante      2     15.4%    0.15
 12      Neeko      2     15.4%    0.15
 13       Sion      2     15.4%    0.15
 14  Jarvan IV      2     15.4%    0.15
 15     Rumble      1      7.7%    0.08
 16      Varus      1      7.7%    0.08
 17      Poppy      1      7.7%    0.08
 18       Nami      1      7.7%    0.08
 19       Gwen      1      7.7%    0.08
 20     Syndra      1      7.7%    0.08
 21      Sivir      1      7.7%    0.08
 22       Bard      1      7.7%    0.08
 23  Seraphine      1      7.7%    0.08
 24    LeBlanc      1      7.7%    0.08
 25   Renekton      1      7.7%    0.08
 26      Karma      1      7.7%    0.08
 27   Xin Zhao      1      7.7%    0.08
 28   Nocturne      1      7.7%    0.08
 29     Ezreal      1      7.7%    0.08
 30       Ashe      1      7.7%    0.08
 31         Vi      1      7.7%    0.08
 32    Trundle      1      7.7%    0.08
 33    Ambessa      1      7.7%    0.08,
 [{'GameId': 'LFL/2026 Season/Invitational_Week 1_1_1',
   'Team1': 'TLN Pirates',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team2',
   'Winner': '2',
   'Patch': '26.2'},
  {'GameId': 'LFL/2026 Season/Invitational_Week 1_9_1',
   'Team1': 'ZYB Esport',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.2'},
  {'GameId': 'LFL/2026 Season/Invitational_Week 2_3_1',
   'Team1': 'Solary',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team1',
   'Winner': '1',
   'Patch': '26.3'},
  {'GameId': 'LFL/2026 Season/Invitational_Week 2_14_1',
   'Team1': 'Galions',
   'Team2': 'Skillcamp',
   'PickingTeamSide': 'Team1',
   'Winner': '1',
   'Patch': '26.3'},
  {'GameId': 'LFL/2026 Season/Invitational_Week 2_18_1',
   'Team1': 'Galions',
   'Team2': 'Vitality.Bee',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.3'},
  {'GameId': 'LFL/2026 Season/Invitational_Week 3_1_1',
   'Team1': 'Galions',
   'Team2': 'BK ROG Esports',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.3'},
  {'GameId': 'LFL/2026 Season/Invitational_Tiebreakers_3_1',
   'Team1': 'Joblife',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.3'},
  {'GameId': 'LFL/2026 Season/Invitational_Round 2_1_1',
   'Team1': 'Galions',
   'Team2': 'Solary',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.4'},
  {'GameId': 'LFL/2026 Season/Spring Split_Week 1_4_1',
   'Team1': 'Solary',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.7'},
  {'GameId': 'LFL/2026 Season/Spring Split_Week 3_4_1',
   'Team1': 'Galions',
   'Team2': 'Joblife',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.8'},
  {'GameId': 'LFL/2026 Season/Spring Split_Week 3_7_1',
   'Team1': 'Galions',
   'Team2': 'Esprit Shōnen',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.8'},
  {'GameId': 'EMEA Masters/2026 Season/Winter_Groups Day 5_4_3',
   'Team1': 'UCAM Esports',
   'Team2': 'Galions',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.5'},
  {'GameId': 'EMEA Masters/2026 Season/Winter_Playoffs Round 1_3_1',
   'Team1': 'Galions',
   'Team2': 'Eintracht Spandau',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.6'}])

---
## 5 · Get players stats from X year 
Precise year and how team or even player

In [10]:
#scout_team(
#    site,
#    team="Team Heretics",
#    roster_year="2026",   # Roster actuel → Ice, Serin, Sheo, Stend, Tracyn
#    stats_year="2025"     # Stats 2025 (peu importe l'équipe d'avant!)
#)

In [11]:
#analyze_team_players_careers(site, "Team Heretics", roster_year="2026")

---
## 5 · Raw DataFrame (ad-hoc queries)
Pull the data once, then query freely.

In [12]:
#df = scrape_draft_data(site, TOURNAMENTS, limit=LIMIT)
#df.head()

In [13]:
# Example: first picks frequency
#df["Team1Pick1"].value_counts().head(20)

In [14]:
# Example: all games where Pantheon was picked
#df[df[[f"Team{t}Pick{i}" for t in [1,2] for i in range(1,6)]].eq("Pantheon").any(axis=1)]

In [15]:
# Example: filter by team + patch, then inspect
#df_sk = filter_dataframe(df, team_filter="SK Gaming", patches=["25.4"])
#df_sk