# Draft Queries
Requires `draft_analysis.py` in the same folder.

In [1]:
from draft_analysis import *

site = connect_to_leaguepedia()

✅ Connexion établie avec Leaguepedia

## ⚙️ Config

In [2]:
TOURNAMENTS = ["LEC 2026 Versus", "LEC 2026 Versus Playoffs"]
PATCHES     = None          # ex: ["25.4", "25.5"] or None for all
TEAM        = "Natus Vincere"          # ex: "SK Gaming" or None for all
LIMIT       = 500          # ex: 100 or None for all

# ── Auto filename builder ────────────────────────────────────────────────────
# Produces a suffix like: LEC2026Versus-LCKCup2026_SKGaming_p25.4-25.5
# Every section below uses it automatically.

def _build_suffix(tournaments=None, team=None, patches=None):
    parts = []
    if tournaments:
        parts.append("-".join(t.replace(" ", "") for t in tournaments))
    if team:
        parts.append(team.replace(" ", ""))
    if patches:
        parts.append("p" + "-".join(patches))
    return "_".join(parts)

SUFFIX = _build_suffix(TOURNAMENTS, TEAM, PATCHES)
print(f"📁 File suffix: {SUFFIX}")

📁 File suffix: LEC2026Versus-LEC2026VersusPlayoffs_NatusVincere

---
## 1 · Draft cards
Visualise every draft as a card. Set `FILTER_CHAMPION` / `HIGHLIGHT_CHAMPION` as needed.

In [3]:
FILTER_CHAMPION    = None   # ex: "Azir"  → only games where Azir appears
HIGHLIGHT_CHAMPION = None   # ex: "Azir"  → highlight Azir in yellow

_suffix = _build_suffix(TOURNAMENTS, TEAM, PATCHES)
if FILTER_CHAMPION:
    _suffix += f"_{FILTER_CHAMPION}"

analyze_drafts(
    site,
    tournaments        = TOURNAMENTS,
    output_filename    = f"drafts_{_suffix}.html",
    team_filter        = TEAM,
    patches            = PATCHES,
    filter_champion    = FILTER_CHAMPION,
    highlight_champion = HIGHLIGHT_CHAMPION,
    limit              = LIMIT,
)

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 66 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (66 matchs)
✅ LEC 2026 Versus: 66 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus Playoffs
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 39 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (39 matchs)
✅ LEC 2026 Versus Playoffs: 39 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 105 matchs
📊 Filtré par équipe: Natus Vincere (18 games)

✅ Page HTML créée: drafts_LEC2026Versus-LEC2026VersusPlayoffs_NatusVincere.html
Total de drafts: 18

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
2,LEC/2026 Season/Versus Season_Week 1_3_1,26.1,Team Heretics,Natus Vincere,2,,Poppy,Pantheon,Varus,Braum,...,K'Sante,Top,Yunara,Bot,Azir,Mid,Qiyana,Jungle,Rakan,Support
8,LEC/2026 Season/Versus Season_Week 1_9_1,26.1,Team Vitality,Natus Vincere,2,,Neeko,Qiyana,Rumble,Jax,...,Taliyah,Mid,Yunara,Bot,Ambessa,Jungle,Alistar,Support,K'Sante,Top
12,LEC/2026 Season/Versus Season_Week 1_13_1,26.1,Fnatic,Natus Vincere,1,,Neeko,Yunara,Sylas,Qiyana,...,K'Sante,Top,Varus,Bot,Akali,Mid,Ambessa,Jungle,Rakan,Support
19,LEC/2026 Season/Versus Season_Week 2_2_1,26.2,Karmine Corp Blue,Natus Vincere,2,,Jayce,Malphite,K'Sante,Xin Zhao,...,Yunara,Bot,Sion,Top,Azir,Mid,Aatrox,Jungle,Alistar,Support
25,LEC/2026 Season/Versus Season_Week 2_8_1,26.2,SK Gaming,Natus Vincere,2,,Malphite,Azir,Orianna,Gwen,...,Taliyah,Mid,Aatrox,Jungle,Aphelios,Bot,Sion,Top,Rakan,Support
34,LEC/2026 Season/Versus Season_Week 2_17_1,26.2,Karmine Corp,Natus Vincere,1,,K'Sante,Sion,Akali,Renekton,...,Aphelios,Bot,Aatrox,Jungle,Taliyah,Mid,Nautilus,Support,Poppy,Top
37,LEC/2026 Season/Versus Season_Week 3_2_1,26.2,GIANTX,Natus Vincere,1,,K'Sante,Azir,Jayce,Yunara,...,Rumble,Top,Wukong,Jungle,Ryze,Mid,Corki,Bot,Pyke,Support
42,LEC/2026 Season/Versus Season_Week 3_7_1,26.2,Natus Vincere,Shifters,1,,Wukong,Taliyah,Varus,Neeko,...,K'Sante,Top,Cassiopeia,Mid,Malphite,Jungle,Nautilus,Support,Kai'Sa,Bot
50,LEC/2026 Season/Versus Season_Week 3_15_1,26.2,Natus Vincere,Los Ratones,1,,Sion,Dr. Mundo,Anivia,Braum,...,Caitlyn,Bot,Pantheon,Jungle,K'Sante,Top,Aurelion Sol,Mid,Karma,Support
57,LEC/2026 Season/Versus Season_Week 4_4_1,26.3,G2 Esports,Natus Vincere,2,,Yunara,Rumble,Kai'Sa,Thresh,...,Orianna,Mid,Ambessa,Jungle,Aphelios,Bot,Nautilus,Support,Sion,Top
63,LEC/2026 Season/Versus Season_Week 4_10_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Aphelios,...,Pantheon,Jungle,Azir,Mid,Aatrox,Top,Neeko,Support,Caitlyn,Bot
66,LEC/2026 Season/Versus Playoffs_Round 1_1_1,26.3,Fnatic,Natus Vincere,2,,Varus,Ambessa,Yunara,Aatrox,...,Azir,Mid,Corki,Bot,Leona,Support,Zaahen,Jungle,K'Sante,Top
67,LEC/2026 Season/Versus Playoffs_Round 1_1_2,26.3,Natus Vincere,Fnatic,1,,Jarvan IV,Poppy,Vi,Gnar,...,Pantheon,Jungle,Taliyah,Mid,Yunara,Bot,Alistar,Support,Jax,Top
74,LEC/2026 Season/Versus Playoffs_Round 2_1_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Pantheon,...,Rumble,Top,Corki,Bot,Yone,Mid,Xin Zhao,Jungle,Nautilus,Support
75,LEC/2026 Season/Versus Playoffs_Round 2_1_2,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Ambessa,Orianna,Caitlyn,...,Dr. Mundo,Jungle,Ryze,Mid,Bard,Support,Miss Fortune,Bot,Gnar,Top
83,LEC/2026 Season/Versus Playoffs_Round 2_3_1,26.3,Natus Vincere,GIANTX,1,,Vi,Jarvan IV,Rumble,Taliyah,...,Pantheon,Jungle,Ezreal,Bot,Gwen,Top,Aurora,Mid,Neeko,Support
84,LEC/2026 Season/Versus Playoffs_Round 2_3_2,26.3,GIANTX,Natus Vincere,1,,Ambessa,Zaahen,Taliyah,Yunara,...,Anivia,Mid,Jarvan IV,Jungle,Gnar,Top,Corki,Bot,Nami,Support
85,LEC/2026 Season/Versus Playoffs_Round 2_3_3,26.3,Natus Vincere,GIANTX,2,,Caitlyn,Poppy,Vi,Nocturne,...,Ornn,Top,Yunara,Bot,Nautilus,Support,Aatrox,Jungle,Taliyah,Mid

---
## 2 · Pick order stats
Pick rate + winrate per role per pick slot (P1 / P2-P3 / P4-P5 for blue, etc.).

In [4]:
analyze_pick_order(
    site,
    tournaments     = TOURNAMENTS,
    output_filename = f"pick_order_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = LIMIT,
)

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 66 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (66 matchs)
✅ LEC 2026 Versus: 66 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus Playoffs
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 39 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (39 matchs)
✅ LEC 2026 Versus Playoffs: 39 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 105 matchs
📊 Filtré par équipe: Natus Vincere (18 games)

✅ Page HTML créée: pick_order_LEC2026Versus-LEC2026VersusPlayoffs_NatusVincere.html
Total de games: 18

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
2,LEC/2026 Season/Versus Season_Week 1_3_1,26.1,Team Heretics,Natus Vincere,2,,Poppy,Pantheon,Varus,Braum,...,K'Sante,Top,Yunara,Bot,Azir,Mid,Qiyana,Jungle,Rakan,Support
8,LEC/2026 Season/Versus Season_Week 1_9_1,26.1,Team Vitality,Natus Vincere,2,,Neeko,Qiyana,Rumble,Jax,...,Taliyah,Mid,Yunara,Bot,Ambessa,Jungle,Alistar,Support,K'Sante,Top
12,LEC/2026 Season/Versus Season_Week 1_13_1,26.1,Fnatic,Natus Vincere,1,,Neeko,Yunara,Sylas,Qiyana,...,K'Sante,Top,Varus,Bot,Akali,Mid,Ambessa,Jungle,Rakan,Support
19,LEC/2026 Season/Versus Season_Week 2_2_1,26.2,Karmine Corp Blue,Natus Vincere,2,,Jayce,Malphite,K'Sante,Xin Zhao,...,Yunara,Bot,Sion,Top,Azir,Mid,Aatrox,Jungle,Alistar,Support
25,LEC/2026 Season/Versus Season_Week 2_8_1,26.2,SK Gaming,Natus Vincere,2,,Malphite,Azir,Orianna,Gwen,...,Taliyah,Mid,Aatrox,Jungle,Aphelios,Bot,Sion,Top,Rakan,Support
34,LEC/2026 Season/Versus Season_Week 2_17_1,26.2,Karmine Corp,Natus Vincere,1,,K'Sante,Sion,Akali,Renekton,...,Aphelios,Bot,Aatrox,Jungle,Taliyah,Mid,Nautilus,Support,Poppy,Top
37,LEC/2026 Season/Versus Season_Week 3_2_1,26.2,GIANTX,Natus Vincere,1,,K'Sante,Azir,Jayce,Yunara,...,Rumble,Top,Wukong,Jungle,Ryze,Mid,Corki,Bot,Pyke,Support
42,LEC/2026 Season/Versus Season_Week 3_7_1,26.2,Natus Vincere,Shifters,1,,Wukong,Taliyah,Varus,Neeko,...,K'Sante,Top,Cassiopeia,Mid,Malphite,Jungle,Nautilus,Support,Kai'Sa,Bot
50,LEC/2026 Season/Versus Season_Week 3_15_1,26.2,Natus Vincere,Los Ratones,1,,Sion,Dr. Mundo,Anivia,Braum,...,Caitlyn,Bot,Pantheon,Jungle,K'Sante,Top,Aurelion Sol,Mid,Karma,Support
57,LEC/2026 Season/Versus Season_Week 4_4_1,26.3,G2 Esports,Natus Vincere,2,,Yunara,Rumble,Kai'Sa,Thresh,...,Orianna,Mid,Ambessa,Jungle,Aphelios,Bot,Nautilus,Support,Sion,Top
63,LEC/2026 Season/Versus Season_Week 4_10_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Aphelios,...,Pantheon,Jungle,Azir,Mid,Aatrox,Top,Neeko,Support,Caitlyn,Bot
66,LEC/2026 Season/Versus Playoffs_Round 1_1_1,26.3,Fnatic,Natus Vincere,2,,Varus,Ambessa,Yunara,Aatrox,...,Azir,Mid,Corki,Bot,Leona,Support,Zaahen,Jungle,K'Sante,Top
67,LEC/2026 Season/Versus Playoffs_Round 1_1_2,26.3,Natus Vincere,Fnatic,1,,Jarvan IV,Poppy,Vi,Gnar,...,Pantheon,Jungle,Taliyah,Mid,Yunara,Bot,Alistar,Support,Jax,Top
74,LEC/2026 Season/Versus Playoffs_Round 2_1_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Pantheon,...,Rumble,Top,Corki,Bot,Yone,Mid,Xin Zhao,Jungle,Nautilus,Support
75,LEC/2026 Season/Versus Playoffs_Round 2_1_2,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Ambessa,Orianna,Caitlyn,...,Dr. Mundo,Jungle,Ryze,Mid,Bard,Support,Miss Fortune,Bot,Gnar,Top
83,LEC/2026 Season/Versus Playoffs_Round 2_3_1,26.3,Natus Vincere,GIANTX,1,,Vi,Jarvan IV,Rumble,Taliyah,...,Pantheon,Jungle,Ezreal,Bot,Gwen,Top,Aurora,Mid,Neeko,Support
84,LEC/2026 Season/Versus Playoffs_Round 2_3_2,26.3,GIANTX,Natus Vincere,1,,Ambessa,Zaahen,Taliyah,Yunara,...,Anivia,Mid,Jarvan IV,Jungle,Gnar,Top,Corki,Bot,Nami,Support
85,LEC/2026 Season/Versus Playoffs_Round 2_3_3,26.3,Natus Vincere,GIANTX,2,,Caitlyn,Poppy,Vi,Nocturne,...,Ornn,Top,Yunara,Bot,Nautilus,Support,Aatrox,Jungle,Taliyah,Mid

---
## 3 · Champion stats by role
Games played, W-L, and winrate for every champion per role.

In [5]:
analyze_champions(
    site,
    tournaments     = TOURNAMENTS,
    output_filename = f"champions_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = LIMIT,
)

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 66 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (66 matchs)
✅ LEC 2026 Versus: 66 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus Playoffs
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 39 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (39 matchs)
✅ LEC 2026 Versus Playoffs: 39 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 105 matchs
📊 Filtré par équipe: Natus Vincere (18 games)

✅ Page web créée: champions_LEC2026Versus-LEC2026VersusPlayoffs_NatusVincere.html
Titre: Champions Stats - Natus Vincere (18 Games)
Total de games analysées: 18

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
2,LEC/2026 Season/Versus Season_Week 1_3_1,26.1,Team Heretics,Natus Vincere,2,,Poppy,Pantheon,Varus,Braum,...,K'Sante,Top,Yunara,Bot,Azir,Mid,Qiyana,Jungle,Rakan,Support
8,LEC/2026 Season/Versus Season_Week 1_9_1,26.1,Team Vitality,Natus Vincere,2,,Neeko,Qiyana,Rumble,Jax,...,Taliyah,Mid,Yunara,Bot,Ambessa,Jungle,Alistar,Support,K'Sante,Top
12,LEC/2026 Season/Versus Season_Week 1_13_1,26.1,Fnatic,Natus Vincere,1,,Neeko,Yunara,Sylas,Qiyana,...,K'Sante,Top,Varus,Bot,Akali,Mid,Ambessa,Jungle,Rakan,Support
19,LEC/2026 Season/Versus Season_Week 2_2_1,26.2,Karmine Corp Blue,Natus Vincere,2,,Jayce,Malphite,K'Sante,Xin Zhao,...,Yunara,Bot,Sion,Top,Azir,Mid,Aatrox,Jungle,Alistar,Support
25,LEC/2026 Season/Versus Season_Week 2_8_1,26.2,SK Gaming,Natus Vincere,2,,Malphite,Azir,Orianna,Gwen,...,Taliyah,Mid,Aatrox,Jungle,Aphelios,Bot,Sion,Top,Rakan,Support
34,LEC/2026 Season/Versus Season_Week 2_17_1,26.2,Karmine Corp,Natus Vincere,1,,K'Sante,Sion,Akali,Renekton,...,Aphelios,Bot,Aatrox,Jungle,Taliyah,Mid,Nautilus,Support,Poppy,Top
37,LEC/2026 Season/Versus Season_Week 3_2_1,26.2,GIANTX,Natus Vincere,1,,K'Sante,Azir,Jayce,Yunara,...,Rumble,Top,Wukong,Jungle,Ryze,Mid,Corki,Bot,Pyke,Support
42,LEC/2026 Season/Versus Season_Week 3_7_1,26.2,Natus Vincere,Shifters,1,,Wukong,Taliyah,Varus,Neeko,...,K'Sante,Top,Cassiopeia,Mid,Malphite,Jungle,Nautilus,Support,Kai'Sa,Bot
50,LEC/2026 Season/Versus Season_Week 3_15_1,26.2,Natus Vincere,Los Ratones,1,,Sion,Dr. Mundo,Anivia,Braum,...,Caitlyn,Bot,Pantheon,Jungle,K'Sante,Top,Aurelion Sol,Mid,Karma,Support
57,LEC/2026 Season/Versus Season_Week 4_4_1,26.3,G2 Esports,Natus Vincere,2,,Yunara,Rumble,Kai'Sa,Thresh,...,Orianna,Mid,Ambessa,Jungle,Aphelios,Bot,Nautilus,Support,Sion,Top
63,LEC/2026 Season/Versus Season_Week 4_10_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Aphelios,...,Pantheon,Jungle,Azir,Mid,Aatrox,Top,Neeko,Support,Caitlyn,Bot
66,LEC/2026 Season/Versus Playoffs_Round 1_1_1,26.3,Fnatic,Natus Vincere,2,,Varus,Ambessa,Yunara,Aatrox,...,Azir,Mid,Corki,Bot,Leona,Support,Zaahen,Jungle,K'Sante,Top
67,LEC/2026 Season/Versus Playoffs_Round 1_1_2,26.3,Natus Vincere,Fnatic,1,,Jarvan IV,Poppy,Vi,Gnar,...,Pantheon,Jungle,Taliyah,Mid,Yunara,Bot,Alistar,Support,Jax,Top
74,LEC/2026 Season/Versus Playoffs_Round 2_1_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Pantheon,...,Rumble,Top,Corki,Bot,Yone,Mid,Xin Zhao,Jungle,Nautilus,Support
75,LEC/2026 Season/Versus Playoffs_Round 2_1_2,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Ambessa,Orianna,Caitlyn,...,Dr. Mundo,Jungle,Ryze,Mid,Bard,Support,Miss Fortune,Bot,Gnar,Top
83,LEC/2026 Season/Versus Playoffs_Round 2_3_1,26.3,Natus Vincere,GIANTX,1,,Vi,Jarvan IV,Rumble,Taliyah,...,Pantheon,Jungle,Ezreal,Bot,Gwen,Top,Aurora,Mid,Neeko,Support
84,LEC/2026 Season/Versus Playoffs_Round 2_3_2,26.3,GIANTX,Natus Vincere,1,,Ambessa,Zaahen,Taliyah,Yunara,...,Anivia,Mid,Jarvan IV,Jungle,Gnar,Top,Corki,Bot,Nami,Support
85,LEC/2026 Season/Versus Playoffs_Round 2_3_3,26.3,Natus Vincere,GIANTX,2,,Caitlyn,Poppy,Vi,Nocturne,...,Ornn,Top,Yunara,Bot,Nautilus,Support,Aatrox,Jungle,Taliyah,Mid

---
## 4 · Ban analysis
What gets banned when a specific champion (or duo) is picked?

In [6]:
# ── Single champion, any pick position ──────────────────────────────────────
CHAMPION = "Azir"

analyze_bans(
    site,
    tournaments     = TOURNAMENTS,
    champion        = CHAMPION,
    output_filename = f"bans_{CHAMPION}_{SUFFIX}.html",
    team_filter     = TEAM,
    patches         = PATCHES,
    limit           = LIMIT,
)

# ── Specific pick slot(s) ────────────────────────────────────────────────────
# CHAMPION = "Corki"
# SLOTS    = ["Team2Pick1", "Team2Pick2"]
# analyze_bans(site, TOURNAMENTS, CHAMPION,
#              pick_moments=SLOTS,
#              output_filename=f"bans_{CHAMPION}_{''.join(SLOTS)}_{SUFFIX}.html",
#              team_filter=TEAM, patches=PATCHES)

# ── Duo (both champs in same team) ───────────────────────────────────────────
# CHAMPION = "Azir"
# DUO      = "Rumble"
# analyze_bans(site, TOURNAMENTS, CHAMPION, champion_duo=DUO,
#              output_filename=f"bans_{CHAMPION}+{DUO}_{SUFFIX}.html",
#              team_filter=TEAM, patches=PATCHES)

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 66 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (66 matchs)
✅ LEC 2026 Versus: 66 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus Playoffs
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 39 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (39 matchs)
✅ LEC 2026 Versus Playoffs: 39 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 105 matchs
📊 Filtré par équipe: Team Heretics (16 games)

================================================================================
📊 ANALYSE DES BANS: AZIR @ ANY POSITION
================================================================================
Tournois: LEC 2026 Versus, LEC 2026 Versus Playoffs
Équipe filtrée: Team Heretics
Games trouvées: 10

✅ Page HTML créée: bans_Azir_LEC2026Versus-LEC2026VersusPlayoffs_TeamHeretics.html
Total de games: 10
Ouvre le fichier dans ton navigateur!

✅ Page HTML créée: bans_Azir_LEC2026Versus-LEC2026VersusPlayoffs_TeamHeretics.html
Total de games: 10
Ouvre le fichier dans ton navigateur!

(      Champion  Count Frequency PerGame
 0       Rumble      4     40.0%    0.40
 1        Neeko      3     30.0%    0.30
 2        Jayce      3     30.0%    0.30
 3     Aphelios      3     30.0%    0.30
 4      Ambessa      3     30.0%    0.30
 5    Dr. Mundo      3     30.0%    0.30
 6        Varus      2     20.0%    0.20
 7        Braum      2     20.0%    0.20
 8      Taliyah      2     20.0%    0.20
 9       Yunara      2     20.0%    0.20
 10    Nautilus      2     20.0%    0.20
 11    Renekton      2     20.0%    0.20
 12     Caitlyn      2     20.0%    0.20
 13       Poppy      1     10.0%    0.10
 14    Pantheon      1     10.0%    0.10
 15     Alistar      1     10.0%    0.10
 16        Bard      1     10.0%    0.10
 17       Rakan      1     10.0%    0.10
 18       Sylas      1     10.0%    0.10
 19        Gnar      1     10.0%    0.10
 20   Jarvan IV      1     10.0%    0.10
 21     K'Sante      1     10.0%    0.10
 22      Aatrox      1     10.0%    0.10
 23    Malphite      1     10.0%    0.10
 24        Lulu      1     10.0%    0.10
 25      Ezreal      1     10.0%    0.10
 26        Jhin      1     10.0%    0.10
 27       Corki      1     10.0%    0.10
 28        Ashe      1     10.0%    0.10
 29  Blitzcrank      1     10.0%    0.10,
         Champion  Count Frequency PerGame
 0          Varus      5     50.0%    0.50
 1          Jayce      4     40.0%    0.40
 2         Yunara      4     40.0%    0.40
 3       Aphelios      3     30.0%    0.30
 4          Neeko      3     30.0%    0.30
 5        Orianna      3     30.0%    0.30
 6          Poppy      3     30.0%    0.30
 7      Jarvan IV      3     30.0%    0.30
 8             Vi      2     20.0%    0.20
 9        Alistar      2     20.0%    0.20
 10      Xin Zhao      2     20.0%    0.20
 11          Bard      2     20.0%    0.20
 12         Rakan      2     20.0%    0.20
 13       Ambessa      1     10.0%    0.10
 14          Ryze      1     10.0%    0.10
 15         Corki      1     10.0%    0.10
 16  Miss Fortune      1     10.0%    0.10
 17      Pantheon      1     10.0%    0.10
 18        Rumble      1     10.0%    0.10
 19        Kai'Sa      1     10.0%    0.10
 20      Renekton      1     10.0%    0.10
 21      Nocturne      1     10.0%    0.10
 22     Dr. Mundo      1     10.0%    0.10
 23         Akali      1     10.0%    0.10
 24  Aurelion Sol      1     10.0%    0.10,
 [{'GameId': 'LEC/2026 Season/Versus Season_Week 1_3_1',
   'Team1': 'Team Heretics',
   'Team2': 'Natus Vincere',
   'PickingTeamSide': 'Team2',
   'Winner': '2',
   'Patch': '26.1'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 1_7_1',
   'Team1': 'Team Heretics',
   'Team2': 'Shifters',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.1'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 1_15_1',
   'Team1': 'GIANTX',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.1'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 2_16_1',
   'Team1': 'G2 Esports',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.2'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 3_1_1',
   'Team1': 'SK Gaming',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team1',
   'Winner': '1',
   'Patch': '26.2'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 3_8_1',
   'Team1': 'Karmine Corp Blue',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.2'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 3_17_1',
   'Team1': 'Movistar KOI',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.2'},
  {'GameId': 'LEC/2026 Season/Versus Season_Week 4_1_1',
   'Team1': 'Fnatic',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team1',
   'Winner': '2',
   'Patch': '26.3'},
  {'GameId': 'LEC/2026 Season/Versus Playoffs_Round 1_3_2',
   'Team1': 'G2 Esports',
   'Team2': 'Team Heretics',
   'PickingTeamSide': 'Team2',
   'Winner': '1',
   'Patch': '26.3'},
  {'GameId': 'LEC/2026 Season/Versus Playoffs_Round 1_5_3',
   'Team1': 'Team Heretics',
   'Team2': 'GIANTX',
   'PickingTeamSide': 'Team2',
   'Winner': '2',
   'Patch': '26.3'}])

---
## 5 · Get players stats from X year 
Precise year and how team or even player

In [7]:
scout_team(
    site,
    team="Team Heretics",
    roster_year="2026",   # Roster actuel → Ice, Serin, Sheo, Stend, Tracyn
    stats_year="2025"     # Stats 2025 (peu importe l'équipe d'avant!)
)

============================================================
🔍 SCOUTING: Team Heretics
   📋 Roster: 2026
   📊 Stats:  2025
============================================================
🔍 Recherche des joueurs de Team Heretics...
✅ 5 joueurs trouvés: Ice (Yoon Sang-hoon), Serin, Sheo, Stend, Tracyn

============================================================
📊 Processing Ice (Yoon Sang-hoon)...

============================================================
🔍 Récupération des stats de Ice (Yoon Sang-hoon)...
============================================================
✅ 50 games trouvées
📊 50 games sur 15 champions

✅ Page HTML créée: ./player_IceYoonSang-hoon_roster2026_stats2025.html

============================================================
📊 Processing Serin...

============================================================
🔍 Récupération des stats de Serin...
============================================================
✅ 86 games trouvées
📊 86 games sur 19 champions

✅ Page HTML créée: ./player_Serin_roster2026_stats2025.html

============================================================
📊 Processing Sheo...

============================================================
🔍 Récupération des stats de Sheo...
============================================================
✅ 54 games trouvées
📊 54 games sur 17 champions

✅ Page HTML créée: ./player_Sheo_roster2026_stats2025.html

============================================================
📊 Processing Stend...

============================================================
🔍 Récupération des stats de Stend...
============================================================
✅ 54 games trouvées
📊 54 games sur 16 champions

✅ Page HTML créée: ./player_Stend_roster2026_stats2025.html

============================================================
📊 Processing Tracyn...

============================================================
🔍 Récupération des stats de Tracyn...
============================================================
✅ 126 games trouvées
📊 126 games sur 20 champions

✅ Page HTML créée: ./player_Tracyn_roster2026_stats2025.html

============================================================
✅ DONE! Generated stats for 5 players
   Team roster: Team Heretics (2026)
   Stats from: 2025
============================================================

{'Ice (Yoon Sang-hoon)':         Champion  Wins  Games  Losses  Winrate
 0          Varus     2      9       7     22.2
 1           Jhin     2      6       4     33.3
 2          Corki     3      6       3     50.0
 3         Ezreal     1      4       3     25.0
 4       Aphelios     2      4       2     50.0
 5           Zeri     2      4       2     50.0
 6           Ashe     0      3       3      0.0
 7          Sivir     2      3       1     66.7
 8           Jinx     1      3       2     33.3
 9   Miss Fortune     1      3       2     33.3
 10        Kai'Sa     0      1       1      0.0
 11       Smolder     0      1       1      0.0
 12         Xayah     1      1       0    100.0
 13        Yunara     0      1       1      0.0
 14         Ziggs     1      1       0    100.0,
 'Serin':         Champion  Wins  Games  Losses  Winrate
 0           Azir     7     11       4     63.6
 1           Ryze     8     10       2     80.0
 2        Taliyah     5      9       4     55.6
 3          Akali     4      8       4     50.0
 4          Jayce     7      8       1     87.5
 5           Hwei     3      6       3     50.0
 6           Ahri     5      6       1     83.3
 7         Aurora     3      5       2     60.0
 8        Orianna     2      5       3     40.0
 9         Viktor     2      4       2     50.0
 10         Sylas     1      3       2     33.3
 11         Ziggs     1      2       1     50.0
 12    Cassiopeia     2      2       0    100.0
 13         Corki     1      2       1     50.0
 14       Ambessa     0      1       1      0.0
 15         Galio     1      1       0    100.0
 16         Annie     0      1       1      0.0
 17  Aurelion Sol     1      1       0    100.0
 18           Mel     0      1       1      0.0,
 'Sheo':      Champion  Wins  Games  Losses  Winrate
 0     Sejuani     5     11       6     45.5
 1      Wukong     1      6       5     16.7
 2        Zyra     1      4       3     25.0
 3     Naafiri     3      4       1     75.0
 4      Maokai     2      4       2     50.0
 5    Xin Zhao     1      4       3     25.0
 6       Brand     1      3       2     33.3
 7      Lillia     2      3       1     66.7
 8     Skarner     1      3       2     33.3
 9   Jarvan IV     0      2       2      0.0
 10         Vi     2      2       0    100.0
 11   Pantheon     0      2       2      0.0
 12   Nocturne     1      2       1     50.0
 13      Ivern     0      1       1      0.0
 14        Jax     0      1       1      0.0
 15    Taliyah     0      1       1      0.0
 16      Poppy     0      1       1      0.0,
 'Stend':         Champion  Wins  Games  Losses  Winrate
 0          Rakan     5     11       6     45.5
 1           Rell     4     11       7     36.4
 2          Leona     2      6       4     33.3
 3          Braum     2      5       3     40.0
 4       Nautilus     2      5       3     40.0
 5   Renata Glasc     2      3       1     66.7
 6          Neeko     1      2       1     50.0
 7        Alistar     0      2       2      0.0
 8         Thresh     2      2       0    100.0
 9           Lulu     0      1       1      0.0
 10         Elise     0      1       1      0.0
 11        Gragas     0      1       1      0.0
 12         Poppy     0      1       1      0.0
 13          Pyke     0      1       1      0.0
 14         Senna     0      1       1      0.0
 15     Seraphine     0      1       1      0.0,
 'Tracyn':     Champion  Wins  Games  Losses  Winrate
 0    K'Sante    13     22       9     59.1
 1     Aatrox    12     19       7     63.2
 2    Ambessa    13     17       4     76.5
 3       Gwen     6     10       4     60.0
 4       Sion     6      9       3     66.7
 5    Camille     5      8       3     62.5
 6      Jayce     4      8       4     50.0
 7        Jax     6      7       1     85.7
 8   Renekton     1      6       5     16.7
 9       Gnar     1      5       4     20.0
 10    Rumble     3      3       0    100.0
 11     Akali     1      2       1     50.0
 12    Irelia     2      2       0    100.0
 13     Vayne     2      2       0    100.0
 14    Aurora     1      1       0    100.0
 15     Galio     0      1       1      0.0
 16  Cho'Gath     0      1       1      0.0
 17      Olaf     0      1       1      0.0
 18  Vladimir     1      1       0    100.0
 19    Wukong     1      1       0    100.0}

In [8]:
analyze_team_players_careers(site, "Team Heretics", roster_year="2026")

============================================================
🎮 FULL CAREER STATS: Team Heretics (2026 roster)
============================================================
🔍 Recherche des joueurs de Team Heretics...
✅ 5 joueurs trouvés: Ice (Yoon Sang-hoon), Serin, Sheo, Stend, Tracyn

============================================================
📊 Processing Ice (Yoon Sang-hoon) (full career)...

============================================================
🔍 Récupération de la carrière complète de Ice (Yoon Sang-hoon)...
============================================================
✅ 322 games trouvées
📊 322 games sur 26 champions
📅 Carrière: 2020 - 2026

✅ Page HTML créée: ./player_IceYoonSang-hoon_career.html

============================================================
📊 Processing Serin (full career)...

============================================================
🔍 Récupération de la carrière complète de Serin...
============================================================
✅ 473 games trouvées
📊 473 games sur 56 champions
📅 Carrière: 2019 - 2026

✅ Page HTML créée: ./player_Serin_career.html

============================================================
📊 Processing Sheo (full career)...

============================================================
🔍 Récupération de la carrière complète de Sheo...
============================================================
✅ 389 games trouvées
📊 389 games sur 39 champions
📅 Carrière: 2020 - 2026

✅ Page HTML créée: ./player_Sheo_career.html

============================================================
📊 Processing Stend (full career)...

============================================================
🔍 Récupération de la carrière complète de Stend...
============================================================
✅ 365 games trouvées
📊 365 games sur 32 champions
📅 Carrière: 2020 - 2026

✅ Page HTML créée: ./player_Stend_career.html

============================================================
📊 Processing Tracyn (full career)...

============================================================
🔍 Récupération de la carrière complète de Tracyn...
============================================================
✅ 333 games trouvées
📊 333 games sur 34 champions
📅 Carrière: 2021 - 2026

✅ Page HTML créée: ./player_Tracyn_career.html

============================================================
✅ DONE! Generated CAREER stats for 5 players from Team Heretics
============================================================

{'Ice (Yoon Sang-hoon)':         Champion  Wins  Games  Losses  Winrate
 0       Aphelios    36     67      31     53.7
 1           Zeri    26     41      15     63.4
 2           Jhin    16     37      21     43.2
 3           Jinx    20     32      12     62.5
 4          Varus     8     21      13     38.1
 5         Ezreal     9     18       9     50.0
 6           Ashe     6     15       9     40.0
 7   Miss Fortune     6     13       7     46.2
 8          Xayah     7     12       5     58.3
 9         Kai'Sa     2     12      10     16.7
 10         Corki     4      8       4     50.0
 11         Sivir     3      7       4     42.9
 12        Lucian     3      6       3     50.0
 13        Samira     4      6       2     66.7
 14         Senna     2      4       2     50.0
 15        Syndra     2      4       2     50.0
 16        Draven     1      4       3     25.0
 17        Yunara     2      3       1     66.7
 18       Kog'Maw     1      2       1     50.0
 19       Kalista     0      2       2      0.0
 20         Ziggs     1      2       1     50.0
 21       Smolder     0      2       2      0.0
 22         Nilah     0      1       1      0.0
 23         Vayne     0      1       1      0.0
 24      Tristana     1      1       0    100.0
 25        Twitch     0      1       1      0.0,
 'Serin':           Champion  Wins  Games  Losses  Winrate
 0             Azir    37     60      23     61.7
 1          Orianna    32     53      21     60.4
 2            Corki    19     33      14     57.6
 3             Ahri    19     29      10     65.5
 4            Sylas    10     19       9     52.6
 5           Viktor     9     17       8     52.9
 6             Ryze    11     17       6     64.7
 7            Akali     8     17       9     47.1
 8     Aurelion Sol    10     15       5     66.7
 9           Syndra     9     15       6     60.0
 10         Taliyah     8     14       6     57.1
 11         LeBlanc     8     14       6     57.1
 12            Hwei     8     14       6     57.1
 13           Jayce     7     12       5     58.3
 14      Cassiopeia    10     11       1     90.9
 15        Tristana     5      9       4     55.6
 16            Yone     5      8       3     62.5
 17          Aurora     4      7       3     57.1
 18           Yasuo     5      7       2     71.4
 19            Ekko     7      7       0    100.0
 20        Kassadin     6      6       0    100.0
 21           Ziggs     4      6       2     66.7
 22             Zoe     5      6       1     83.3
 23          Aatrox     3      5       2     60.0
 24    Twisted Fate     4      5       1     80.0
 25            Zeri     3      4       1     75.0
 26        Renekton     3      4       1     75.0
 27          Irelia     3      4       1     75.0
 28          Gragas     2      4       2     50.0
 29       Seraphine     4      4       0    100.0
 30          Lucian     1      3       2     33.3
 31         Lee Sin     1      3       2     33.3
 32           Galio     2      3       1     66.7
 33           Annie     1      3       2     33.3
 34          Anivia     1      2       1     50.0
 35         Morgana     0      2       2      0.0
 36          Draven     2      2       0    100.0
 37         Camille     2      2       0    100.0
 38         K'Sante     0      2       2      0.0
 39          Kai'Sa     1      2       1     50.0
 40          Veigar     2      2       0    100.0
 41           Swain     1      2       1     50.0
 42             Vex     2      2       0    100.0
 43            Ornn     1      2       1     50.0
 44          Rumble     0      2       2      0.0
 45          Qiyana     0      2       2      0.0
 46  Nunu & Willump     2      2       0    100.0
 47         Ambessa     0      1       1      0.0
 48           Fiora     0      1       1      0.0
 49           Diana     1      1       0    100.0
 50            Bard     1      1       0    100.0
 51     Mordekaiser     1      1       0    100.0
 52           Karma     0      1       1      0.0
 53             Mel     0      1       1      0.0
 54    Miss Fortune     1      1       0    100.0
 55           Viego     1      1       0    100.0,
 'Sheo':      Champion  Wins  Games  Losses  Winrate
 0     Sejuani    25     49      24     51.0
 1    Xin Zhao    27     44      17     61.4
 2     Lee Sin    21     35      14     60.0
 3          Vi    19     28       9     67.9
 4      Maokai    20     27       7     74.1
 5      Wukong    12     24      12     50.0
 6       Poppy    10     18       8     55.6
 7    Volibear     6     13       7     46.2
 8       Viego     7     12       5     58.3
 9     Taliyah     5     11       6     45.5
 10      Ivern     6     10       4     60.0
 11     Rumble     6     10       4     60.0
 12       Zyra     4      9       5     44.4
 13     Lillia     5      9       4     55.6
 14     Gragas     2      8       6     25.0
 15  Jarvan IV     1      7       6     14.3
 16     Graves     2      7       5     28.6
 17      Diana     3      7       4     42.9
 18    Naafiri     3      5       2     60.0
 19      Brand     1      5       4     20.0
 20  Dr. Mundo     3      5       2     60.0
 21    Trundle     1      5       4     20.0
 22   Pantheon     0      4       4      0.0
 23   Nocturne     1      4       3     25.0
 24    Karthus     1      4       3     25.0
 25        Zed     1      3       2     33.3
 26      Elise     3      3       0    100.0
 27       Udyr     1      3       2     33.3
 28    Skarner     1      3       2     33.3
 29        Jax     2      3       1     66.7
 30       Rell     1      3       2     33.3
 31    Hecarim     1      2       1     50.0
 32    Nidalee     1      2       1     50.0
 33    Morgana     1      2       1     50.0
 34     Aatrox     0      1       1      0.0
 35       Ekko     0      1       1      0.0
 36    Ambessa     1      1       0    100.0
 37      Jayce     0      1       1      0.0
 38     Qiyana     1      1       0    100.0,
 'Stend':         Champion  Wins  Games  Losses  Winrate
 0       Nautilus    39     66      27     59.1
 1          Rakan    31     55      24     56.4
 2        Alistar    21     40      19     52.5
 3           Rell    22     39      17     56.4
 4          Leona    18     33      15     54.5
 5         Thresh    14     20       6     70.0
 6   Renata Glasc    13     18       5     72.2
 7          Braum     8     17       9     47.1
 8          Senna     9     12       3     75.0
 9          Yuumi     6      8       2     75.0
 10          Lulu     2      7       5     28.6
 11         Karma     2      5       3     40.0
 12          Pyke     2      4       2     50.0
 13         Milio     2      4       2     50.0
 14         Galio     2      4       2     50.0
 15          Nami     3      4       1     75.0
 16    Tahm Kench     1      3       2     33.3
 17         Neeko     1      3       2     33.3
 18    Blitzcrank     2      3       1     66.7
 19         Poppy     1      2       1     50.0
 20          Ashe     1      2       1     50.0
 21         Amumu     1      2       1     50.0
 22  Heimerdinger     1      2       1     50.0
 23        Gragas     1      2       1     50.0
 24        Zilean     0      2       2      0.0
 25     Seraphine     0      2       2      0.0
 26       Camille     1      1       0    100.0
 27         Elise     0      1       1      0.0
 28        Maokai     0      1       1      0.0
 29          Sona     0      1       1      0.0
 30         Taric     0      1       1      0.0
 31      Xin Zhao     1      1       0    100.0,
 'Tracyn':         Champion  Wins  Games  Losses  Winrate
 0        K'Sante    22     48      26     45.8
 1         Aatrox    21     35      14     60.0
 2       Renekton    16     32      16     50.0
 3           Gnar    14     29      15     48.3
 4           Gwen    16     24       8     66.7
 5        Camille    12     22      10     54.5
 6        Ambessa    16     21       5     76.2
 7          Jayce     9     18       9     50.0
 8            Jax    12     17       5     70.6
 9           Sion     7     12       5     58.3
 10         Fiora     4      8       4     50.0
 11        Rumble     4      8       4     50.0
 12        Gragas     4      7       3     57.1
 13         Akali     2      6       4     33.3
 14          Yone     6      6       0    100.0
 15        Irelia     3      4       1     75.0
 16       Sejuani     1      4       3     25.0
 17          Ornn     2      4       2     50.0
 18        Kennen     1      3       2     33.3
 19        Graves     2      3       1     66.7
 20         Vayne     3      3       0    100.0
 21      Vladimir     2      2       0    100.0
 22        Aurora     2      2       0    100.0
 23       Shyvana     1      2       1     50.0
 24          Olaf     0      2       2      0.0
 25    Tryndamere     1      2       1     50.0
 26  Twisted Fate     1      2       1     50.0
 27        Akshan     1      1       0    100.0
 28      Cho'Gath     0      1       1      0.0
 29         Galio     0      1       1      0.0
 30         Kayle     1      1       0    100.0
 31         Quinn     1      1       0    100.0
 32         Varus     0      1       1      0.0
 33        Wukong     1      1       0    100.0}

---
## 5 · Raw DataFrame (ad-hoc queries)
Pull the data once, then query freely.

In [9]:
df = scrape_draft_data(site, TOURNAMENTS, limit=LIMIT)
df.head()

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 66 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (66 matchs)
✅ LEC 2026 Versus: 66 matchs avec picks/bans

============================================================
🔍 Traitement du tournoi: LEC 2026 Versus Playoffs
============================================================

🔍 Étape 1: Récupération des matchs...
✅ 39 matchs trouvés

🔍 Étape 2: Récupération des picks & bans...
   Requête 1/1... ✓ (39 matchs)
✅ LEC 2026 Versus Playoffs: 39 matchs avec picks/bans

============================================================
🔍 Étape 3: Fusion des données de tous les tournois...
============================================================

✅ TOTAL: Données de draft assemblées pour 105 matchs

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
0,LEC/2026 Season/Versus Season_Week 1_1_1,26.1,Fnatic,Los Ratones,1,,Neeko,Sion,Malphite,Nami,...,Corki,Bot,Jarvan IV,Jungle,Ryze,Mid,Kled,Top,Braum,Support
1,LEC/2026 Season/Versus Season_Week 1_2_1,26.1,GIANTX,Shifters,1,,Sylas,Qiyana,Malphite,Nautilus,...,Azir,Mid,Wukong,Jungle,K'Sante,Top,Ezreal,Bot,Bard,Support
2,LEC/2026 Season/Versus Season_Week 1_3_1,26.1,Team Heretics,Natus Vincere,2,,Poppy,Pantheon,Varus,Braum,...,K'Sante,Top,Yunara,Bot,Azir,Mid,Qiyana,Jungle,Rakan,Support
3,LEC/2026 Season/Versus Season_Week 1_4_1,26.1,SK Gaming,Team Vitality,2,,Malphite,Azir,Poppy,Nautilus,...,Corki,Bot,Pantheon,Jungle,Taliyah,Mid,Rakan,Support,Aatrox,Top
4,LEC/2026 Season/Versus Season_Week 1_5_1,26.1,Karmine Corp,Karmine Corp Blue,1,,Malphite,Pantheon,Ambessa,Alistar,...,Taliyah,Mid,Varus,Bot,Vi,Jungle,Aatrox,Top,Nautilus,Support

In [10]:
# Example: first picks frequency
df["Team1Pick1"].value_counts().head(20)

Team1Pick1
Azir         23
Rumble       15
Ryze         13
Yunara       10
Orianna       9
Varus         9
Jayce         5
Vi            5
Dr. Mundo     3
Pantheon      2
Ambessa       2
Malphite      1
Corki         1
Xin Zhao      1
Aatrox        1
Zaahen        1
Sion          1
Taliyah       1
Lucian        1
Neeko         1
Name: count, dtype: int64

In [11]:
# Example: all games where Pantheon was picked
df[df[[f"Team{t}Pick{i}" for t in [1,2] for i in range(1,6)]].eq("Pantheon").any(axis=1)]

,GameId,Patch,Team1,Team2,Winner,MatchHistory,Team1Ban1,Team1Ban2,Team1Ban3,Team1Ban4,...,Team2Pick1,Team2Role1,Team2Pick2,Team2Role2,Team2Pick3,Team2Role3,Team2Pick4,Team2Role4,Team2Pick5,Team2Role5
3,LEC/2026 Season/Versus Season_Week 1_4_1,26.1,SK Gaming,Team Vitality,2,,Malphite,Azir,Poppy,Nautilus,...,Corki,Bot,Pantheon,Jungle,Taliyah,Mid,Rakan,Support,Aatrox,Top
6,LEC/2026 Season/Versus Season_Week 1_7_1,26.1,Team Heretics,Shifters,2,,Neeko,Taliyah,Yunara,Bard,...,Ryze,Mid,Wukong,Jungle,K'Sante,Top,Corki,Bot,Rell,Support
13,LEC/2026 Season/Versus Season_Week 1_14_1,26.1,Team Vitality,Karmine Corp Blue,1,,Malphite,Orianna,Varus,Yunara,...,Ryze,Mid,Pantheon,Jungle,Aatrox,Top,Aphelios,Bot,Bard,Support
22,LEC/2026 Season/Versus Season_Week 2_5_1,26.2,Karmine Corp,SK Gaming,1,,Irelia,Vi,Akali,Gwen,...,Jinx,Bot,Pantheon,Jungle,Ekko,Mid,Nautilus,Support,Kled,Top
23,LEC/2026 Season/Versus Season_Week 2_6_1,26.2,Fnatic,Movistar KOI,2,,Neeko,Yunara,Taliyah,Rakan,...,Rumble,Top,Pantheon,Jungle,Akali,Mid,Alistar,Support,Corki,Bot
30,LEC/2026 Season/Versus Season_Week 2_13_1,26.2,SK Gaming,Karmine Corp Blue,1,,Malphite,Akali,Orianna,Aurora,...,Yunara,Bot,Jarvan IV,Jungle,Aatrox,Top,Azir,Mid,Rakan,Support
31,LEC/2026 Season/Versus Season_Week 2_14_1,26.2,Los Ratones,Shifters,1,,Rumble,Varus,Cassiopeia,Ambessa,...,Taliyah,Mid,Vi,Jungle,Neeko,Support,Lucian,Bot,Nidalee,Top
34,LEC/2026 Season/Versus Season_Week 2_17_1,26.2,Karmine Corp,Natus Vincere,1,,K'Sante,Sion,Akali,Renekton,...,Aphelios,Bot,Aatrox,Jungle,Taliyah,Mid,Nautilus,Support,Poppy,Top
36,LEC/2026 Season/Versus Season_Week 3_1_1,26.2,SK Gaming,Team Heretics,1,,Dr. Mundo,Jarvan IV,Jayce,Aphelios,...,K'Sante,Top,Aatrox,Jungle,Orianna,Mid,Jhin,Bot,Karma,Support
38,LEC/2026 Season/Versus Season_Week 3_3_1,26.2,Fnatic,Shifters,2,,Neeko,Rumble,Vi,Bard,...,Jhin,Bot,Azir,Mid,Skarner,Jungle,Rell,Support,Rek'Sai,Top
39,LEC/2026 Season/Versus Season_Week 3_4_1,26.2,G2 Esports,Karmine Corp Blue,1,,Yunara,Rumble,Aatrox,Ambessa,...,Pantheon,Jungle,Taliyah,Mid,Corki,Bot,K'Sante,Top,Nautilus,Support
40,LEC/2026 Season/Versus Season_Week 3_5_1,26.2,Team Vitality,Karmine Corp,1,,Jarvan IV,Azir,Yunara,Bard,...,Rumble,Top,Pantheon,Jungle,Cassiopeia,Mid,Alistar,Support,Sivir,Bot
45,LEC/2026 Season/Versus Season_Week 3_10_1,26.2,Movistar KOI,SK Gaming,1,,Akali,Yone,Irelia,Neeko,...,Pantheon,Jungle,Sion,Top,Ryze,Mid,Caitlyn,Bot,Elise,Support
48,LEC/2026 Season/Versus Season_Week 3_13_1,26.2,Fnatic,Karmine Corp Blue,1,,Neeko,Varus,Taliyah,Aphelios,...,Pantheon,Jungle,Galio,Mid,K'Sante,Top,Kai'Sa,Bot,Nautilus,Support
50,LEC/2026 Season/Versus Season_Week 3_15_1,26.2,Natus Vincere,Los Ratones,1,,Sion,Dr. Mundo,Anivia,Braum,...,Caitlyn,Bot,Pantheon,Jungle,K'Sante,Top,Aurelion Sol,Mid,Karma,Support
52,LEC/2026 Season/Versus Season_Week 3_17_1,26.2,Movistar KOI,Team Heretics,2,,Dr. Mundo,Ambessa,Malphite,Neeko,...,K'Sante,Top,Orianna,Mid,Yunara,Bot,Xin Zhao,Jungle,Braum,Support
57,LEC/2026 Season/Versus Season_Week 4_4_1,26.3,G2 Esports,Natus Vincere,2,,Yunara,Rumble,Kai'Sa,Thresh,...,Orianna,Mid,Ambessa,Jungle,Aphelios,Bot,Nautilus,Support,Sion,Top
58,LEC/2026 Season/Versus Season_Week 4_5_1,26.3,Movistar KOI,Team Vitality,2,,Malphite,Orianna,Dr. Mundo,Nautilus,...,Pantheon,Jungle,Yunara,Bot,Zoe,Mid,K'Sante,Top,Neeko,Support
59,LEC/2026 Season/Versus Season_Week 4_6_1,26.3,Karmine Corp,GIANTX,1,,Neeko,Vi,Yone,Caitlyn,...,Taliyah,Mid,Pantheon,Jungle,Gnar,Top,Corki,Bot,Rakan,Support
60,LEC/2026 Season/Versus Season_Week 4_7_1,26.3,Team Vitality,Los Ratones,1,,Ryze,Caitlyn,Nami,Lillia,...,Sion,Top,Corki,Bot,Yone,Mid,Bard,Support,Sylas,Jungle
63,LEC/2026 Season/Versus Season_Week 4_10_1,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Orianna,Ambessa,Aphelios,...,Pantheon,Jungle,Azir,Mid,Aatrox,Top,Neeko,Support,Caitlyn,Bot
67,LEC/2026 Season/Versus Playoffs_Round 1_1_2,26.3,Natus Vincere,Fnatic,1,,Jarvan IV,Poppy,Vi,Gnar,...,Pantheon,Jungle,Taliyah,Mid,Yunara,Bot,Alistar,Support,Jax,Top
69,LEC/2026 Season/Versus Playoffs_Round 1_2_2,26.3,Movistar KOI,Team Vitality,1,,Ezreal,Zoe,Varus,Jhin,...,Rumble,Top,Jarvan IV,Jungle,Nautilus,Support,Ahri,Mid,Jinx,Bot
71,LEC/2026 Season/Versus Playoffs_Round 1_3_2,26.3,G2 Esports,Team Heretics,1,,Rumble,Yunara,Ambessa,Jhin,...,Azir,Mid,Pantheon,Jungle,Nautilus,Support,Miss Fortune,Bot,Gnar,Top
75,LEC/2026 Season/Versus Playoffs_Round 2_1_2,26.3,Movistar KOI,Natus Vincere,1,,Yunara,Ambessa,Orianna,Caitlyn,...,Dr. Mundo,Jungle,Ryze,Mid,Bard,Support,Miss Fortune,Bot,Gnar,Top
83,LEC/2026 Season/Versus Playoffs_Round 2_3_1,26.3,Natus Vincere,GIANTX,1,,Vi,Jarvan IV,Rumble,Taliyah,...,Pantheon,Jungle,Ezreal,Bot,Gwen,Top,Aurora,Mid,Neeko,Support
95,LEC/2026 Season/Versus Playoffs_Round 4_2_1,26.3,Movistar KOI,Karmine Corp,1,,Yunara,Bard,Renekton,Karma,...,Varus,Top,Pantheon,Jungle,Orianna,Mid,Ezreal,Bot,Alistar,Support
102,LEC/2026 Season/Versus Playoffs_Finals_1_3,26.3,Karmine Corp,G2 Esports,1,,Aphelios,Neeko,Vi,Kai'Sa,...,Ornn,Top,Pantheon,Jungle,Sylas,Mid,Corki,Bot,Rell,Support

In [12]:
# Example: filter by team + patch, then inspect
df_sk = filter_dataframe(df, team_filter="SK Gaming", patches=["25.4"])
df_sk

📊 Filtré par équipe: SK Gaming (11 games)
📊 Filtré par patches: ['25.4'] -> normalisé: ['25.4'] (0 games)

Empty DataFrame
Columns: [GameId, Patch, Team1, Team2, Winner, MatchHistory, Team1Ban1, Team1Ban2, Team1Ban3, Team1Ban4, Team1Ban5, Team1Pick1, Team1Role1, Team1Pick2, Team1Role2, Team1Pick3, Team1Role3, Team1Pick4, Team1Role4, Team1Pick5, Team1Role5, Team2Ban1, Team2Ban2, Team2Ban3, Team2Ban4, Team2Ban5, Team2Pick1, Team2Role1, Team2Pick2, Team2Role2, Team2Pick3, Team2Role3, Team2Pick4, Team2Role4, Team2Pick5, Team2Role5]
Index: []

[0 rows x 36 columns]